#!/usr/bin/env python3
"""Inspect/clean GitHub Actions artifacts or explicitly scaffold daily cleanup."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import actions_artifact_gc as gc

WORKFLOW = Path(".github/workflows/subfloor-artifact-cleanup.yml")


def workflow_text(days: int = 7) -> str:
    # Embed the same tested, stdlib-only implementation. Forks do not track the
    # engine; privileged cleanup must never checkout or execute their PR code.
    source = Path(gc.__file__).read_text()
    source += """
try:
    raise SystemExit(main())
except (CleanupError, KeyError, TypeError, ValueError) as exc:
    raise SystemExit(f"actions-artifacts: {exc}") from exc
"""
    header = """# Fork-owned: generated by sc actions-artifacts setup-ci; review and commit.
name: Subfloor artifact cleanup
on:
  schedule:
    - cron: '23 4 * * *'
  workflow_dispatch:
    inputs:
      apply:
        description: Delete eligible artifacts (unchecked performs a dry run)
        type: boolean
        default: false
permissions:
  actions: write
concurrency:
  group: subfloor-artifact-cleanup
  cancel-in-progress: false
jobs:
  cleanup:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      ARTIFACT_RETENTION_DAYS: '__DAYS__'
      APPLY: ${{ github.event_name == 'schedule' || inputs.apply }}
    steps:
      - name: Sweep old artifacts from completed runs
        shell: bash
        run: |
          args=(--repo "$GH_REPO" --older-than-days "$ARTIFACT_RETENTION_DAYS")
          if [ "$APPLY" = true ]; then args+=(--apply); fi
          python3 - "${args[@]}" <<'SUBFLOOR_ARTIFACT_PY'
""".replace("__DAYS__", str(days))
    return header + "".join("          " + line + "\n" for line in source.splitlines()) + "          SUBFLOOR_ARTIFACT_PY\n"


def setup_ci(root: Path, days: int) -> Path:
    target = root / WORKFLOW
    # Refuse symlinked directories as well as an existing workflow. The caller
    # owns the file after creation; install/update never refresh or seed it.
    if any(path.is_symlink() for path in (root / ".github", target.parent, target)):
        raise gc.CleanupError("refusing a symlinked workflow path")
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        with target.open("x") as handle:
            handle.write(workflow_text(days))
    except FileExistsError as exc:
        raise gc.CleanupError(f"refusing to overwrite {target}") from exc
    return target


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if args and args[0] == "cleanup":
        return gc.main(args[1:])
    parser = argparse.ArgumentParser(prog="sc actions-artifacts", description=__doc__)
    parser.add_argument("mode", choices=("cleanup", "setup-ci"))
    _mode, remainder = parser.parse_known_args(args)
    setup = argparse.ArgumentParser(prog="sc actions-artifacts setup-ci")
    setup.add_argument("--older-than-days", type=gc.positive_days, default=7)
    options = setup.parse_args(remainder)
    target = setup_ci(Path.cwd(), options.older_than_days)
    print(f"Created {target}. Review, commit and merge to enable daily cleanup.")
    print("Manual dispatch defaults to dry run. Set upload-artifact retention-days to match.")
    return 0


if __name__ == "__main__":
    from cli_entry import run_cli

    try:
        raise SystemExit(run_cli(main))
    except (gc.CleanupError, KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"actions-artifacts: {exc}") from exc
