#!/usr/bin/env python3
"""Generate the skills seed migration from `assets/skills/`.

Skills are SYSTEM content: the catalogue propagates to every fork. So it is
seeded via a migration (ordered, pulled downstream), not the per-instance
snapshot. Migrations are declarative `.sql` — no Python runs against a fork's
DB — so this script is the *authoring* tool that compiles the authored skill
sources into that `.sql`.

Source of truth for a skill = `assets/skills/<name>/SKILL.md`:

    ---
    name: db_map
    description: one-line summary (used in the boot SKILLS block + catalogue)
    category: substrate          # optional
    command: ./sc snapshot       # optional
    common: true                 # optional (default true)
    ---
    <markdown body → skills.content>

Output: `migrations/0001_seed_skills.sql` — an idempotent
DELETE-the-seeded-names-then-INSERT block. Re-running regenerates it byte-for-
byte. The migration is keyed by filename in the ledger, so it applies once per
fork; regenerating its *contents* and re-running `./sc rebuild` re-seeds from
scratch (rebuild drops the DB), while a fork that already stamped it pulls the
change only if the filename advances — bump the number for a breaking re-seed,
or keep it for additive catalogue growth picked up on a fresh rebuild.

Usage:
    python3 .super-coder/scripts/seed_skills.py
    ./sc seed-skills
"""
from __future__ import annotations

import sys
from pathlib import Path

ENGINE = Path(__file__).resolve().parents[1]
SKILLS_DIR = ENGINE / "assets" / "skills"
OUT = ENGINE / "migrations" / "0001_seed_skills.sql"


def sql_str(v) -> str:
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def parse_skill(path: Path) -> dict:
    """Parse a SKILL.md: YAML-ish frontmatter (flat key: value) + body."""
    text = path.read_text()
    if not text.startswith("---"):
        sys.exit(f"seed_skills: {path} has no frontmatter")
    _, fm, body = text.split("---", 2)
    meta: dict[str, str] = {}
    for line in fm.strip().splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    if "name" not in meta:
        sys.exit(f"seed_skills: {path} frontmatter missing `name`")
    common = meta.get("common", "true").lower() not in ("false", "0", "no")
    return {
        "name": meta["name"],
        "description": meta.get("description"),
        "category": meta.get("category"),
        "command": meta.get("command"),
        "common": 1 if common else 0,
        "content": body.strip(),
    }


def main() -> int:
    if not SKILLS_DIR.exists():
        sys.exit(f"seed_skills: no {SKILLS_DIR}")
    skills = [parse_skill(d / "SKILL.md")
              for d in sorted(SKILLS_DIR.iterdir())
              if (d / "SKILL.md").exists()]
    if not skills:
        sys.exit("seed_skills: no skills found under assets/skills/")

    names = ", ".join(sql_str(s["name"]) for s in skills)
    lines = [
        "-- super-coder skills seed — GENERATED by scripts/seed_skills.py.",
        "-- System content: the catalogue propagates to every fork. Idempotent —",
        "-- deletes the seeded names then re-inserts. Do not hand-edit; author",
        "-- assets/skills/<name>/SKILL.md then `./sc seed-skills`.",
        "",
        "BEGIN;",
        "",
        f"DELETE FROM skills WHERE name IN ({names});",
        "",
    ]
    for s in skills:
        lines.append(
            "INSERT INTO skills (name, description, category, command, common, content) "
            f"VALUES (\n  {sql_str(s['name'])},\n  {sql_str(s['description'])},\n  "
            f"{sql_str(s['category'])},\n  {sql_str(s['command'])},\n  {s['common']},\n  "
            f"{sql_str(s['content'])}\n);"
        )
        lines.append("")
    lines.append("COMMIT;")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"seed_skills: wrote {OUT.relative_to(ENGINE.parent)} "
          f"({len(skills)} skill(s): {', '.join(s['name'] for s in skills)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
