#!/usr/bin/env python3
"""Serialize this fork's per-instance content + memory to text.

Dumps the per-instance tables of the live `shell_db.db` to
`.super-coder/snapshot/content.sql` as a deterministic, idempotent SQL script:
each table is `DELETE`d then re-`INSERT`ed in primary-key order, so re-running
produces a byte-identical file (clean git diffs) and loading it is repeatable.

This is the *per-instance* serialization — it rebuilds THIS repo's content and
stays local. It never propagates to forks (that is migrations' job). System
content (skills) is seeded from assets/ via migrations, not dumped here.

FK checks are off during load (SQLite default), so dump order is for readability
only, not correctness.

Usage:
    python3 .super-coder/scripts/snapshot.py
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

ENGINE = Path(__file__).resolve().parents[1]
DB_PATH = ENGINE / "shell_db.db"
OUT_PATH = ENGINE / "snapshot" / "content.sql"

# Per-instance tables, parents-before-children for readability. The `skills`
# catalogue and `schema_migrations` ledger are excluded — they are SYSTEM
# content seeded from migrations, not one fork's snapshot. `shell_skills` IS
# here, though: which shell is *granted* a skill is a fork-local decision (the
# bodies propagate via migration; the grants do not). It loads after `shells`
# (its FK target) and after the skills migration has run, so both ends exist.
PER_INSTANCE_TABLES = [
    "users",
    "shells",
    "shell_identity_entries",
    "shell_decisions",
    "shell_memory_archives",
    "roadmap",
    "documents",
    "flags",
    "projects",
    "project_shells",
    "shell_skills",
]


def quote(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def table_exists(con: sqlite3.Connection, name: str) -> bool:
    return con.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone() is not None


def dump_shell_skills(con: sqlite3.Connection) -> list[str]:
    """Grants resolved by skill NAME, not raw skill_id. Skill ids are positional
    (they shift when the catalogue grows), so a raw-id dump would bind a fork's
    grants to the wrong skills after an update. Resolving by name at load time
    makes grants id-churn-proof."""
    rows = con.execute(
        "SELECT ss.shell_id, s.name FROM shell_skills ss "
        "JOIN skills s ON s.skill_id = ss.skill_id ORDER BY ss.shell_id, s.name"
    ).fetchall()
    lines = ["DELETE FROM shell_skills;"]
    for shell_id, name in rows:
        lines.append(
            f"INSERT INTO shell_skills (shell_id, skill_id) "
            f"SELECT {shell_id}, skill_id FROM skills WHERE name={quote(name)};")
    lines.append("")
    return lines


def dump_table(con: sqlite3.Connection, table: str) -> list[str]:
    if table == "shell_skills":
        return dump_shell_skills(con)
    cols = [r[1] for r in con.execute(f"PRAGMA table_info({table})")]
    if not cols:
        return []
    collist = ", ".join(cols)
    rows = con.execute(f"SELECT {collist} FROM {table} ORDER BY rowid").fetchall()
    lines = [f"DELETE FROM {table};"]
    for row in rows:
        vals = ", ".join(quote(v) for v in row)
        lines.append(f"INSERT INTO {table} ({collist}) VALUES ({vals});")
    lines.append("")
    return lines


def main() -> int:
    if not DB_PATH.exists():
        raise SystemExit(f"snapshot: no live DB at {DB_PATH} — run `make rebuild` first.")
    con = sqlite3.connect(DB_PATH)
    try:
        out = [
            "-- super-coder per-instance snapshot — GENERATED by scripts/snapshot.py.",
            "-- Idempotent: DELETE-then-INSERT per table, PK order. Loaded by rebuild.py.",
            "-- This file rebuilds THIS repo's content + memory; it stays local (never",
            "-- propagates to forks). Do not hand-edit — author via the shell or GUI, then",
            "-- `make snapshot`.",
            "",
            "BEGIN;",
            "",
        ]
        for table in PER_INSTANCE_TABLES:
            if table_exists(con, table):
                out.extend(dump_table(con, table))
        out.append("COMMIT;")
        OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUT_PATH.write_text("\n".join(out) + "\n")
    finally:
        con.close()
    print(f"snapshot: wrote {OUT_PATH.relative_to(ENGINE.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
