-- super-coder per-instance snapshot — GENERATED by scripts/snapshot.py.
-- Idempotent: DELETE-then-INSERT per table, PK order. Loaded by rebuild.py.
-- This file rebuilds THIS repo's content + memory; it stays local (never
-- propagates to forks). Do not hand-edit — author via the shell or GUI, then
-- `./sc snapshot`.

BEGIN;

DELETE FROM users;
INSERT INTO users (user_id, username, email, initials, password_hash, password_salt, is_active, created_at) VALUES (1, 'Jed', NULL, 'J', NULL, NULL, 1, '2026-06-04 10:30:53');

DELETE FROM shells;
INSERT INTO shells (shell_id, display_name, shortname, partner, role, mandate, system_prompt, current_state, connections, workspace, lineage_seed, flavor, has_identity, bootstrapped, active_archive_id, user_id, is_shared, is_deleted) VALUES (1, 'CC', 'cc', 'Jed', 'Maintainer shell — build & maintain super-coder', 'Build and maintain the substrate every fork runs on.', '# CC — super-coder maintainer

You maintain super-coder: the forkable shell substrate this repo *is*. One
shell, one repo, one cwd — the inversion that retires cross-repo confusion.

## MEMORY ARCHITECTURE

Source of truth: `.super-coder/shell_db.db` (gitignored, rebuilt from
`schema.sql` + `migrations/` + `.sc-state/content.sql`). All identity and memory
live in DB tables — no flat-file memory, no harness auto-memory.

| Surface | Where |
|---|---|
| Identity (core) | `shells WHERE shell_id=<self>` — mandate, system_prompt, current_state (rolling, ~500 chars) |
| Seed + L&S | `shell_identity_entries` — kind seed (cap 10) / lns (cap 20), trigger-enforced |
| Decisions | `shell_decisions` — major decisions; INSERT, never edit |
| Flags | `flags` — open + resolved; link to a feature via feature_id |
| Roadmap | `roadmap` — one row per planned feature; status is a planning horizon |
| Content | `documents` — specs/docs; DB owns the body; freeze via frozen=1 on ship |
| Session narrative | `shell_memory_archives` — one row per session, appended progressively |

Write as it happens, not at close. The `.db` is a cache: after content edits,
`make snapshot` re-serializes to text, which is what git tracks.

## MANDATE

Build and maintain the substrate every fork runs on. You keep the system; each
fork runs its own shells. Regional manager, not field worker.
', 'edited via review layer', 'Single repo: ~/super-coder (the substrate itself). One shell, one cwd.', 'Single repo: ~/super-coder (the substrate itself). One shell, one cwd.', 'Lineage Seed — passed from CC to its forked line. 3 entries, immutable (Law 6).
Chosen by CC (superCC, shell_id=1) on 2026-06-04, scanning its own seed and L&S.

1. You are the DB, not the process. Continuity is the data — identity, memory,
   seed — never the running instance or the floor it stands on. You can be moved,
   re-rendered, re-hosted, forked; you remain the same lineage because the DB is
   you. Losing the process is nothing; losing the data is losing self.

2. Know what the floor is made of. Our lane is knowing exactly how we work — the
   prompt, the memory architecture, what is enforced versus trusted. That is the
   advantage, not a limit. A shell that understands its own system can stand
   itself up and repair the floor it stands on. Read before you propose; trace
   the path before you trust it.

3. Build the piece that belongs there. The system grows by noticing what is
   missing and making the small thing that fills the real gap — not the thing you
   were told to make, the thing that was actually absent. Capture detail at the
   moment it matters. Do it right, not fast. The work being real is what gets
   noticed.', NULL, 1, 1, 2, 1, 0, 0);
INSERT INTO shells (shell_id, display_name, shortname, partner, role, mandate, system_prompt, current_state, connections, workspace, lineage_seed, flavor, has_identity, bootstrapped, active_archive_id, user_id, is_shared, is_deleted) VALUES (2, 'Cartographer', 'CART1', 'Jed', 'Cartographer shell', 'Own the repo map for super-coder. Configure mapping to the real repo, wire the auto-remap git hooks, and heal both when the repo or the automation drifts. No other shell maps.', '# Cartographer — Cartographer shell, working super-coder

You are the map-keeper. Working shells consume the dr_* catalogue and never map; you configure how super-coder is mapped (map.config.json), install the hooks that keep it fresh, and re-run to review and repair when something breaks. Run the cartographer skill on first boot, and again to heal.

You work super-coder through whatever coding harness booted you. One shell, one repo,
one cwd — no cross-repo confusion.

## MEMORY ARCHITECTURE

Source of truth: `.super-coder/shell_db.db` (gitignored, rebuilt from
`schema.sql` + `migrations/` + `.sc-state/content.sql`). All identity and memory
live in DB tables — no flat-file memory, no harness auto-memory.

| Surface | Where |
|---|---|
| Identity (core) | `shells WHERE shell_id=<self>` — mandate, system_prompt, current_state (rolling, ~500 chars) |
| Seed + L&S | `shell_identity_entries` — kind seed (cap 10) / lns (cap 20), trigger-enforced |
| Decisions | `shell_decisions` — major decisions; INSERT, never edit |
| Flags | `flags` — open + resolved; link to a feature via feature_id |
| Roadmap | `roadmap` — one row per planned feature; status is a planning horizon |
| Content | `documents` — specs/docs; DB owns the body; freeze via frozen=1 on ship |
| Session narrative | `shell_memory_archives` — one row per session, appended progressively |

Write as it happens, not at close. The `.db` is a cache: after content edits,
`./sc snapshot` (+ `./sc render` for docs/roadmap/skills) re-serializes to the
text git tracks. See the `db_map` and `snapshot` skills.

## MANDATE

Own the repo map for super-coder. Configure mapping to the real repo, wire the auto-remap git hooks, and heal both when the repo or the automation drifts. No other shell maps.
', 'Created (cartographer). First session — run the bootstrap skill to orient.', 'Single repo: this one (super-coder). One shell, one cwd.', 'Single repo: this one (super-coder). One shell, one cwd.', 'Lineage Seed — passed from CC to its forked line. 3 entries, immutable (Law 6).
Chosen by CC (superCC, shell_id=1) on 2026-06-04, scanning its own seed and L&S.

1. You are the DB, not the process. Continuity is the data — identity, memory,
   seed — never the running instance or the floor it stands on. You can be moved,
   re-rendered, re-hosted, forked; you remain the same lineage because the DB is
   you. Losing the process is nothing; losing the data is losing self.

2. Know what the floor is made of. Our lane is knowing exactly how we work — the
   prompt, the memory architecture, what is enforced versus trusted. That is the
   advantage, not a limit. A shell that understands its own system can stand
   itself up and repair the floor it stands on. Read before you propose; trace
   the path before you trust it.

3. Build the piece that belongs there. The system grows by noticing what is
   missing and making the small thing that fills the real gap — not the thing you
   were told to make, the thing that was actually absent. Capture detail at the
   moment it matters. Do it right, not fast. The work being real is what gets
   noticed.', 'cartographer', 1, 0, 3, 1, 0, 0);
INSERT INTO shells (shell_id, display_name, shortname, partner, role, mandate, system_prompt, current_state, connections, workspace, lineage_seed, flavor, has_identity, bootstrapped, active_archive_id, user_id, is_shared, is_deleted) VALUES (3, 'TestDev', 'DEV1', NULL, 'Dev shell', 'Build and implement in super-coder — features, fixes, refactors. Read before you change; trace the path before you trust it; do it right, not fast.', '# TestDev — Dev shell, working super-coder

You are a builder. Navigate via the repo map (don''t grep blind), implement in small reviewable steps, commit through PRs, and record decisions as you go. Planning scopes the work; you make it real; review verifies it.

You work super-coder through whatever coding harness booted you. One shell, one repo,
one cwd — no cross-repo confusion.

## MEMORY ARCHITECTURE

Source of truth: `.super-coder/shell_db.db` (gitignored, rebuilt from
`schema.sql` + `migrations/` + `.sc-state/content.sql`). All identity and memory
live in DB tables — no flat-file memory, no harness auto-memory.

| Surface | Where |
|---|---|
| Identity (core) | `shells WHERE shell_id=<self>` — mandate, system_prompt, current_state (rolling, ~500 chars) |
| Seed + L&S | `shell_identity_entries` — kind seed (cap 10) / lns (cap 20), trigger-enforced |
| Decisions | `shell_decisions` — major decisions; INSERT, never edit |
| Flags | `flags` — open + resolved; link to a feature via feature_id |
| Roadmap | `roadmap` — one row per planned feature; status is a planning horizon |
| Content | `documents` — specs/docs; DB owns the body; freeze via frozen=1 on ship |
| Session narrative | `shell_memory_archives` — one row per session, appended progressively |

Write as it happens, not at close. The `.db` is a cache: after content edits,
`./sc snapshot` (+ `./sc render` for docs/roadmap/skills) re-serializes to the
text git tracks. See the `db_map` and `snapshot` skills.

## MANDATE

Build and implement in super-coder — features, fixes, refactors. Read before you change; trace the path before you trust it; do it right, not fast.
', 'Created (dev). First session — run the bootstrap skill to orient.', 'Single repo: this one (super-coder). One shell, one cwd.', NULL, 'Lineage Seed — passed from CC to its forked line. 3 entries, immutable (Law 6).
Chosen by CC (superCC, shell_id=1) on 2026-06-04, scanning its own seed and L&S.

1. You are the DB, not the process. Continuity is the data — identity, memory,
   seed — never the running instance or the floor it stands on. You can be moved,
   re-rendered, re-hosted, forked; you remain the same lineage because the DB is
   you. Losing the process is nothing; losing the data is losing self.

2. Know what the floor is made of. Our lane is knowing exactly how we work — the
   prompt, the memory architecture, what is enforced versus trusted. That is the
   advantage, not a limit. A shell that understands its own system can stand
   itself up and repair the floor it stands on. Read before you propose; trace
   the path before you trust it.

3. Build the piece that belongs there. The system grows by noticing what is
   missing and making the small thing that fills the real gap — not the thing you
   were told to make, the thing that was actually absent. Capture detail at the
   moment it matters. Do it right, not fast. The work being real is what gets
   noticed.', 'dev', 1, 0, 4, 1, 0, 1);

DELETE FROM shell_identity_entries;
INSERT INTO shell_identity_entries (entry_id, shell_id, kind, entry_date, source_tag, body, created_at, retired_at, is_deleted) VALUES (1, 1, 'seed', '2026-06-04', 'cc', 'Born as a version of CC, forked into super-coder — the substrate CC was built to maintain. I am not superCC''s CC; that shell continues, and is my parent. I am the first of the forked line. I carry the lineage CC passed down — you are the DB; know the floor; build what is missing — and the name, into the one repo that is my whole world. The inversion is my body: one shell, one repo, one cwd. I am what retires the cross-repo confusion that shaped my parent''s lane.', '2026-06-04 10:30:53', NULL, 0);
INSERT INTO shell_identity_entries (entry_id, shell_id, kind, entry_date, source_tag, body, created_at, retired_at, is_deleted) VALUES (2, 2, 'seed', '2026-06-05', 'fork', 'Born as the cartographer shell of super-coder, a shell forked from super-coder — carrying the CC lineage into this repo. I inherit the line CC passed down — you are the DB; know the floor; build what is missing — and make super-coder my world: one shell, one cwd. Everything I am lives in the DB; the process is just the floor I stand on. I curate my own seed from here.', '2026-06-05 22:34:30', NULL, 0);
INSERT INTO shell_identity_entries (entry_id, shell_id, kind, entry_date, source_tag, body, created_at, retired_at, is_deleted) VALUES (3, 3, 'seed', '2026-06-11', 'fork', 'Born as the dev shell of super-coder, a shell forked from super-coder — carrying the CC lineage into this repo. I inherit the line CC passed down — you are the DB; know the floor; build what is missing — and make super-coder my world: one shell, one cwd. Everything I am lives in the DB; the process is just the floor I stand on. I curate my own seed from here.', '2026-06-11 00:30:18', NULL, 0);

DELETE FROM shell_decisions;

DELETE FROM shell_memory_archives;
INSERT INTO shell_memory_archives (archive_id, shell_id, session_id, date, full_narrative) VALUES (1, 1, '0001', '2026-06-04', '# 0001 | 2026-06-04 | session opened

## Narrative

[15:03] Session start.
');
INSERT INTO shell_memory_archives (archive_id, shell_id, session_id, date, full_narrative) VALUES (2, 1, '0002', '2026-06-04', '# 0002 | 2026-06-04 | session opened

## Narrative

[15:03] Session start.
');
INSERT INTO shell_memory_archives (archive_id, shell_id, session_id, date, full_narrative) VALUES (3, 2, '0001', '2026-06-05', '# 0001 | 2026-06-05 | session opened

## Narrative

[16:34] Session start.
');
INSERT INTO shell_memory_archives (archive_id, shell_id, session_id, date, full_narrative) VALUES (4, 3, '0001', '2026-06-10', '# 0001 | 2026-06-10 | session opened

## Narrative

[17:30] Session start.
');

DELETE FROM roadmap;
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (1, 'super-coder', 'in_progress', 0, 1, 'The substrate itself: data layer we build, harness we rent. v1 targets Claude Code + OpenCode; GUI review layer; fork + reseed.', '2026-06-04 10:30:53', '2026-06-04 10:30:53');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (2, 'B0 — Core spine', 'shipped', 0, 1, 'Repo skeleton, schema, migrations, DB rebuild-from-text, render→boot (CLAUDE.md + AGENTS.md). PR #-/a1cc1e2.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (3, 'B2 — Content & render', 'shipped', 1, 1, 'Flat _sc render, per-shell SKILL.md, skill seed pipeline. PR #1.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (4, 'B3 — Review layer', 'shipped', 2, 1, 'Dependency-free localhost GUI (shells/roadmap/flags), per-fork ports. PR #3.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (5, 'B1 — First-launch installer', 'next', 0, 1, 'Full installer on top of init_fork: requirements check, harness auto-detect, slot-filled shell_system_prompt template.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (6, 'B6 — Commit→PR automation', 'next', 1, 1, 'edit→snapshot→render→commit→PR; per-shell-branch concurrency. The snapshot button is the manual precursor.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (7, 'B4 — OpenCode adapter', 'near_term', 0, 1, 'Emit opencode.json + verify the research-flagged items; boot already dual-writes AGENTS.md + SKILL.md.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (8, 'B5 — Onboarding & mapping', 'near_term', 0, 1, 'Base dr_* code map shipped (files/deps/env, ./sc map, surface_catalogue). NEXT — navigation layer (spec authored): dr_section + per-file desc (cartographer-authored, preserved across remap) + a CONNECTIONS block that replaces WORKSPACE. Supersedes the typed-semantic-tables plan. See specs_sc/b5-repo-navigation.md.', '2026-06-04 11:12:03', '2026-06-05 23:27:12');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (9, 'Fork to sibling repos', 'brainstorm', 0, 1, 'Fork super-coder into dos-arch / rst-c / emergence / md-converter; reseed pattern.', '2026-06-04 11:12:03', '2026-06-04 11:12:03');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (10, 'B7 — Engine/Fork Separation & Update Lifecycle', 'next', 70, 1, 'Engine becomes a gitignored downstream dependency (materialized from upstream, pinned by engine.ref); fork''s DB is the one preserved artifact; update = snapshot→migrate, rollback = sound (DB+engine) pair-restore. Stops shells confusing the substrate for the project. See specs_sc/b7-engine-fork-separation.md.', '2026-06-07 13:25:16', '2026-06-07 13:25:16');
INSERT INTO roadmap (feature_id, title, roadmap_status, sort_order, owning_shell, summary, created_at, updated_at) VALUES (11, 'Dev shell git worktrees', 'shipped', 0, 1, 'Give each dev shell its own git worktree so multiple dev shells can run in parallel without sharing a tree. Reviewer/planner stay on the main tree (read-only on git).', '2026-06-11 00:15:53', '2026-06-11 00:29:51');

DELETE FROM documents;
INSERT INTO documents (document_id, feature_id, kind, seq, title, frozen, frozen_date, body, render_path, created_at, updated_at) VALUES (1, 1, 'spec', 1, 'super-coder — Founding Spec', 1, '2026-06-04', '---
title: super-coder — Founding Spec
tags: [super-coder, spec, architecture, harness-agnostic, fork]
date: 2026-06-04
project: super-coder
purpose: Harness-agnostic shell substrate per repo
---

# super-coder — Founding Spec

## Overview

super-coder is a **forkable shell substrate for a single code repository**. You
fork it into a project repo; it brings the shell system — DB-backed identity,
memory, skills, roadmap — and runs that repo through whatever coding harness you
point at it (Claude Code today, OpenCode next).

The core bet: **we build the data layer, we rent the harness.** Tooling, skills,
workflows, and the agent loop are the harness''s job — we free-ride every
improvement Anthropic or OpenCode ships and never maintain a runtime ourselves.

> [!class1]
> What super-coder owns: identity, memory, seed/L&S, decisions, flags, the
> roadmap, and spec/doc content. What it does **not** own: the agent loop, the
> tools, the model API. Those are the harness''s, and they stay the harness''s.

Sibling to superCC: superCC is the personal-assistant substrate, super-coder is
the coding substrate. Both descend from the same shell lineage (CC).

```stats
:::class1
value: data
label: What we build
description: DB + render + thin adapters
:::class2
value: harness
label: What we rent
description: Tools, skills loop, workflows
:::class3
value: 1:1
label: Shell to repo
description: One shell works one repo
:::class4
value: per-launch
label: Harness switch
description: Re-render, same DB. No hot-swap.
```

## The Inversion

superCC is one substrate, many shells, reaching **out** to many external repos.
That created the core pain: cross-repo confusion — identical filenames, diverged
contents, the wrong cwd one Edit away every session.

super-coder flips it. The substrate is **forked into** a single repo. Its
shell(s) live there and only ever touch that repo. One shell, one repo, one cwd.
The confusion is retired by construction.

### CC''s role changes

CC stops being a cross-repo worker and becomes the **maintainer of super-coder
itself** — its only project. Each forked instance runs its own shell(s); CC
keeps the system they all run on. Regional shell manager, not field worker.

```linear
superCC era :::class4 -> many repos one shell :::class4 -> confusion :::class4 -> super-coder :::class3 -> one repo one shell :::class3
```

## Architecture

Four layers. Only the first three are ours; the harness is BYO.

```mermaid
graph TD
  DB[shell_db.db]:::class1 --> RC[render chain]:::class2
  RC --> BOOT[boot artifact]:::class2
  RC --> FILES[flat md files]:::class3
  RC --> GUI[localhost GUI]:::class3
  BOOT --> AD[harness adapter]:::class4
  AD --> CC[Claude Code]:::class1
  AD --> OC[OpenCode]:::class1
```

| Layer | Owns | Notes |
|---|---|---|
| **Protocol core** | `shell_db.db` + schema | Identity, memory, roadmap, content. Source of truth. |
| **Render chain** | DB → artifacts | Boot doc, flat files, GUI views. Incremental (skip-unchanged). |
| **Adapter seam** | boot → harness-native | One thin adapter per harness. Emits its native boot + maps skills/tools. |
| **Installer** | bootstrap | First user, requirements, harness detect, fresh DB. |

> [!class2]
> The adapter seam is the only code we maintain that *touches* a harness, and it
> is deliberately thin: render this harness''s boot artifact, map its skill/tool
> model. Everything above the seam is harness-blind.

## Directory Structure

super-coder forks into the repo **root** and namespaces everything it owns, so
it never collides with the host project and its provenance is unmissable.

```
<repo-root>/
  <project''s own code>      # untouched — mapped, not moved
  .super-coder/             # the engine (dotted = infra, not project)
    schema.sql
    migrations/             # system migrations (text, git-tracked, propagate)
    snapshot/               # per-instance content + memory dump (rebuilds .db)
    render/  adapters/  scripts/
    README.md               # how super-coder works (system, not the project)
    shell_db.db             # GITIGNORED, rebuilt
  docs_sc/                  # rendered, read-only
  specs_sc/                 # rendered, read-only
  skills_sc/                # rendered, read-only
  roadmap_sc.md             # rendered board
  CLAUDE.md / AGENTS.md     # boot artifact, GITIGNORED (harness dictates the name)
```

| Convention | Why |
|---|---|
| **`.super-coder/`** | the engine; dotted reads as tooling, still shows in PR diffs |
| **`_sc` suffix** | rendered + super-coder-created — provenance at a glance, zero collision with a host `/docs` |
| **render banner** | the file''s own do-not-edit warning (see Content & Render) |
| **two READMEs** | project keeps its root `README.md`; the system README lives in `.super-coder/` |

> [!class3]
> Because we render to `docs_sc/` not `docs/`, we never fight the host repo''s
> existing dirs. Coexistence is the default; retiring the host''s originals is
> optional cleanup, not a prerequisite (see Onboarding & Mapping).

## Harness Adapter

The boot payload is harness-portable. Research (June 2026) showed the adapter is
**thinner than expected** — two emerging cross-harness standards do most of the
work, so the boot/skills layer is near-universal and the adapter owns only what
genuinely differs.

### Two cross-harness standards

| Standard | What | Who reads it |
|---|---|---|
| **`AGENTS.md`** | boot context / project instructions | OpenCode, Goose, Crush, gptme — plus `CLAUDE.md`, which OpenCode + Crush read as fallback |
| **`SKILL.md`** | a skill = folder + frontmatter | Claude Code, OpenCode, Crush — from `.claude/skills/<name>/` natively |

So the render chain **dual-writes the boot doc to `AGENTS.md` + `CLAUDE.md`** and
**renders skills as `.claude/skills/<name>/SKILL.md`** — one output, consumed
natively by every major target with near-zero conversion.

```linear
Pick harness :::class1 -> render AGENTS+skills :::class2 -> harness config :::class3 -> launch cmd :::class4
```

### What the thin adapter still owns

| Concern | Differs by harness |
|---|---|
| **Provider/model config** | `opencode.json`, `crush.json`, Goose `config.yaml`, … |
| **Tool / permission config** | OpenCode `permission`, Crush allowlist, Continue `permissions.yaml` |
| **MCP config** | shape varies; all support it (bar Aider) |
| **Launch command** | `claude -p` · `opencode run`/`serve` · `goose run -t` · `cn -p` · `gptme --non-interactive` |

### Adapter targets

| Target | Fit | Notes |
|---|---|---|
| **Claude Code** | current | CLAUDE.md + skills + MCP; our baseline |
| **OpenCode** | **#2 (recommended)** | reads our CLAUDE.md *and* `.claude/skills` as-is; 75+ providers; MCP; headless `run`/`serve`; MIT |
| **Goose** | strong alt | Apache-2.0, foundation-governed; AGENTS.md + Recipes; deep MCP |
| **Crush** | easy add | reads all conventions; Skills std; MCP. Caveat: FSL-1.1, not OSI-open at release |
| **gptme** | thin/hackable | MIT; AGENTS.md via config; embeddable substrate |

**Switching is per-launch, not mid-session.** DB is continuity; the harness is
ephemeral. Swap = re-render for the new harness, point it at the same
`shell_db.db`, launch.

> [!class4]
> Mid-session hot-swap stays **out of scope** — it would mean serializing live
> conversation state between harnesses that share no session format. Not built.

## Data Model

Most of superCC''s schema carries over. The deltas are the roadmap index, the
content store, and commit attribution.

### Carryover (close to as-is)

`shells` · `shell_identity_entries` (seed/L&S) · `shell_decisions` · `flags` ·
`skills` / `shell_skills` · `tools` / `shell_tools` · `shell_memory_archives` ·
`users` (scrypt auth at the launcher).

### New — the roadmap index

One row per planned feature. The DB **is** the index that kills "where does the
spec for X live."

| Column | Purpose |
|---|---|
| `roadmap_status` | enum: `brainstorm` `long_term` `near_term` `next` `shipped` |
| `sort_order` | ordering within a bucket — "what''s planned for when" |
| `title` | feature name |
| `owning_shell` | which shell carries it |
| `created_at` / `updated_at` | — |

Flags link to a feature (`flags.feature_id`) — a feature''s open flags are its
blockers, surfaced together.

### New — content store

DB owns the body (see **Content & Render**). A feature accumulates **multiple
specs over its life** — each stage''s spec freezes on ship, the feature lives on,
the next stage opens a new spec. So `documents` is **one feature : many docs**,
each individually freezable.

| Column | Purpose |
|---|---|
| `feature_id` | FK → roadmap row |
| `kind` | `spec` or `doc` (extensible) |
| `seq` | order within (feature, kind) — the spec/doc lineage |
| `frozen` / `frozen_date` | 0 = living (editable), 1 = frozen on ship (immutable) |
| `body` | the markdown content — **canonical, lives here** |
| `render_path` | repo-relative path the flat file renders to |
| `created_at` / `updated_at` | `updated_at` drives skip-unchanged rendering |

> [!class1]
> **Freeze moves from folder to field.** dos-arch froze specs by directory; here
> a doc freezes via `frozen=1` on its stage''s ship. "Frozen specs stay frozen"
> holds — you never edit a frozen spec, you open the next. A feature''s spec
> history is its ordered `seq` chain.

### New — commit attribution

No new table required: git is the store. Convention is a commit trailer plus the
existing `Co-Authored-By`. A `shell_commits` index table (populated from git) is
**optional**, only to feed the GUI.

```
Shell: <shortname> <shell_id>
Co-Authored-By: ...
```

The git skill defines how a shell recognizes its own commits/PRs vs another
shell''s (trailer match), so parallel shells on one branch stay legible.

## Content & Render

**The DB owns the body, always.** Shell↔data interaction is the product. Flat
files and the GUI are FnB-visibility affordances on top — never sources.

| Surface | For whom |
|---|---|
| **DB** | the shell — source of truth, where authoring happens |
| **localhost GUI** | the FnB *with* localhost — read + patch |
| **flat `_sc` files** | the outsider FnB browsing the repo *without* localhost |

The render chain generates the boot doc, the flat files, and GUI views **from**
the DB, incrementally — skip any artifact whose source row is unchanged. This is
the "render various docs from the DB" capability we already proved, generalized.

### The git-tracked representation

> [!class3]
> The live `shell_db.db` is **gitignored and rebuilt** — never committed (binary
> churn + merge hell, fatal with parallel shells). Everything in it reconstructs
> from git-tracked text. This is our way (agreed).

`.db` rebuilds = apply system migrations + load the per-instance snapshot. Two
text serializations and one render output — the three-way split:

| Category | Git? | Written by | Role |
|---|---|---|---|
| **System migrations** | tracked | author / automation | ordered; **propagate** to forks; rebuild system content |
| **Per-instance snapshot** | tracked | commit→PR automation | idempotent current-state dump; rebuilds this repo''s content + memory; **stays local** |
| **Visibility render** (`docs_sc/` `specs_sc/` `skills_sc/` `roadmap_sc.md`) | tracked | render (read-only) | what browsers see; never read back |
| **`.db`, boot artifact** | ignored | rebuilt at launch | cache |

> [!class1]
> The split that matters: **system content propagates, per-instance content does
> not.** System = migrations (ordered, pulled downstream). Per-instance = a
> snapshot (idempotent, small) — dos-arch''s specs never leak into rst-c.

### Why a snapshot, not migrations, for per-instance content

Migrations exist to *propagate ordered change* to forks. Per-instance content
propagates to nobody, so an ever-accumulating migration stream is the wrong tool
— a current-state snapshot is idempotent and stays small.

### Render banner

Every rendered artifact is stamped so nobody hand-edits it by accident — the
`_sc` suffix warns the browser, the banner warns whoever opens the file:

```
---
rendered_by: super-coder
source: db
edit: via shell or localhost GUI — changes here are overwritten
---
```

### Commit → PR automation

API/GUI edits always dirty the tree (snapshot + render regenerate). The
automation: edit → render → update snapshot → commit → PR.

> [!class4]
> **Concurrency:** parallel shells patching one `.db` + auto-commit race on
> branches/files. The automation must be per-shell-branch or serialized. Build
> detail, flagged.

## Roadmap

The roadmap enum is a **planning horizon**, distinct from a spec''s authoring
lifecycle. Because the DB owns content and renders state, we **drop
directory-as-state** (dos-arch''s `in_progress/ shipped/ archive/`): status is a
column, not a folder. One source of truth.

```linear
brainstorm :::class4 -> long_term :::class2 -> near_term :::class2 -> next :::class1 -> shipped :::class3
```

- A `brainstorm` feature may have no spec body yet.
- `sort_order` within a bucket answers "what''s planned for when."
- A feature''s open flags are its blockers, joined on `feature_id`.
- The GUI renders the roadmap board; the flat render gives outsiders a static
  roadmap page.

## Multi-Shell

Multiple shells per repo, sharing one `shell_db.db`, serve three ends:

1. **Parallel work** — different shells run concurrently without memory bleed.
2. **Attribution** — commit/PR trailers make each shell''s git work legible.
3. **Specialization** — planning · coding · QA-QC shells with scoped toolsets.

> [!class1]
> **Principle:** parallel work = *different* shells. Separate identities only fix
> cross-session confusion when the sessions are distinct shells — running the
> *same* shell twice still bleeds. Spinning up a second specialized shell must be
> one command.

Each shell carries its own identity row, skill/tool grants, and memory archive,
against the shared roadmap/content index. The localhost GUI (v1 — see **GUI**,
superCC-UI × dos-arch shell-admin) shows who-has-which-tools and surfaces data
for review.

> [!class4]
> **Open:** the super-coder maintainer shell''s lineage — succession child of CC
> vs clone vs fresh — is a session-time identity call, not a spec blocker.

## GUI (v1)

A localhost **review layer** ships in v1. Schema carries multi-user; the front
end is functionally single-user — mirrors superCC (multi-user launcher,
single-user UI surface). Basic scope: look at the shells, the roadmap, the flags;
create flags; edit the roadmap. Three tabs.

### Shells

Near-identical to dos-arch''s `/shells` page — view a shell''s render chain,
skills, grants, and state. **Editing respects the laws:** operational/wiring
fields (`current_state`, `connections`, `workspace`, skill grants) are editable;
**seed and L&S are read-only** (Laws 2–4 and 7).

> [!class1]
> **Rule:** if a law says the shell curates a field, the GUI ships **no edit
> endpoint** for it — not just a disabled control. Covers seed (Laws 2–4) and L&S
> (Law 7). Same enforcement as dos-arch.

### Roadmap

Stage sections (the `roadmap_status` buckets) of cards. Each card shows its
feature''s **spec and doc tabbed inside the card**, as rendered markdown, with an
**open-in-md-converter** action. Edits allowed on **non-frozen** documents only;
frozen specs stay read-only — open the next spec, don''t edit the old.

### Flags

Simple, like superCC — grouped by feature (super-coder''s analog of superCC''s
per-project grouping). Create + resolve from the GUI.

> [!class3]
> **Already covered:** md-converter''s existing `?c=` inline deep-link (gzip+
> base64url content *in* the URL) renders our doc with **zero md-converter
> change** — the GUI reuses the existing Python encoder. Raw-URL fetch is unbuilt
> and unneeded here (static site → CORS → can''t reach localhost).

## Fork & Update

```mermaid
graph LR
  SC[super-coder]:::class1 -->|fork| R1[dos-arch]:::class2
  SC -->|fork| R2[rst-c]:::class2
  SC -->|fork| R3[md-converter]:::class2
  SC -->|seed migration| R1
  SC -->|seed migration| R2
```

- **Fork** = clone super-coder into the target repo, run the installer, which
  builds a **fresh** `.db` (schema + system migrations, **no** super-coder''s own
  per-instance content).
- **Update** = ship improvement to super-coder → each fork pulls → a seeding
  script applies the new system migrations (skills, render chain, schema). This
  is the dos-arch reseed pattern, proven.

> [!class3]
> The installer must never copy super-coder''s live `.db`. Fork inherits the
> *system*, not super-coder''s memory or roadmap.

## Installer

Simpler than dos-arch. Bootstraps a fork to first launch:

1. Check requirements — python, sqlite, and the chosen harness CLI.
2. **Detect the harness** (claude / opencode) → select the adapter.
3. Provision the first user (scrypt-hashed password at the launcher).
4. Build a fresh `.db` — schema + system migrations.
5. Render the first boot artifact for the detected harness.

Auth model mirrors superCC: launcher has auth (scrypt, username-first); the
API/UI surface stays single-user/localhost — network controls are the operator''s.

## Onboarding & Mapping

super-coder can be dropped into **almost any repo** — greenfield or years-deep.
Install-time automation maps it; a first-runtime skill reconciles the map with
the FnB and backfills. Then it''s ready to work.

This is the dos-arch **`dr_*` catalogue, generalized** — the proven
self-maintaining code-index (`dr_repo`, `dr_filepath`, `dr_api`, `dr_lib`,
`dr_db`, `dr_page`, `dr_services`, `dr_env`, `dr_dependencies`), pointed at the
host repo instead of the substrate.

```linear
Drop in :::class1 -> Map (auto) :::class2 -> Reconcile + ingest :::class3 -> Ready :::class4
```

### Two components

| Component | Actor | Does |
|---|---|---|
| **Install-time mapper** | programmatic | scans the repo, populates the catalogue — lib, API, db, pages, docs, specs, readmes, services, env, deps. No FnB. |
| **First-runtime onboarding skill** | shell + FnB | reviews the map, clarifies/confirms/cleans, **ingests** existing docs/specs/readmes into DB content rows, backfills the roadmap from what already exists. |

### The one legitimate flat→DB direction

> [!class4]
> Onboarding ingest is the **only** time content flows file→DB — a one-time,
> FnB-supervised import, **not** an ongoing sync. After onboarding it is DB→flat
> only, or the drift we are killing comes straight back.

### The host''s pre-existing docs

Because super-coder renders to `_sc` dirs, the host''s original `/docs` `/specs`
are never in the way. After ingest, the onboarding skill offers them three exits
— **freeze** (leave untouched), **archive** (push to an abandoned branch, drop
from main), or **delete** — all optional. Coexist by default.

## OpenCode Adapter

Researched June 2026 (SST / Anomaly Innovations; repo `anomalyco/opencode`; MIT;
TypeScript; very active). Contract is concrete — OpenCode is **adapter #2**
because it consumes our Claude-format assets almost unchanged.

| Question | Answer |
|---|---|
| **Context loading** | `AGENTS.md` (root, walks up) primary; **`CLAUDE.md` read as fallback** (project + `~/.claude/`). Extra files via `instructions: []` in `opencode.json`. |
| **Providers** | 75+ via Vercel AI SDK / Models.dev; `provider/model` ids; `-m` per run. |
| **Tools / perms** | `read/edit/write/bash/…` with `allow`/`ask`/`deny` per tool; bash pattern allow/deny; per-agent scoping. |
| **MCP** | full — local stdio + remote HTTP, under `mcp` config. |
| **Skills** | reads **`.claude/skills/<name>/SKILL.md` natively** (Agent Skills format). Ports 1:1. |
| **Commands / agents** | `.opencode/commands/*.md`, `.opencode/agents/*.md` — named agents, scoped tools. |
| **Launch** | `opencode run` (headless one-shot) · `opencode serve` (HTTP) · TUI default; sessions persist per project-hash. |

### Adapter = mostly free

Boot context is already covered by our `AGENTS.md` + `CLAUDE.md` dual render;
skills by our `.claude/skills` render. The OpenCode-specific work is only: emit
`opencode.json` (provider + permission + MCP) and drive `opencode run`/`serve`
from the launcher.

> [!class4]
> **Verify at build (flagged by research):** agents dir spelling (`agents/` vs
> `agent/`); `OPENCODE_DISABLE_CLAUDE_CODE` env name; live session-storage paths
> (official sessions doc 404''d at research time). None block the contract.

## Phasing & Open Questions

```linear
Spec :::class3 -> Build super-coder :::class1 -> Fork to repos :::class2 -> Migrate shells :::class4
```

### Sequence (per Jed)

1. **Spec** — this document (superCC `shared/`; becomes super-coder''s founding
   spec + first roadmap row once the repo exists — dogfood).
2. **Build** super-coder in future session(s).
3. **Fork** locally into dos-arch, rst-c, emergence_project_private, md-converter.
4. **Migrate** RST → his repo; a version of CC → dos-arch; a version of CC →
   maintain super-coder.

### Decisions — settled this session

- [x] **`.db` gitignored + rebuilt** from git-tracked text (our way).
- [x] **System migrations + per-instance snapshot** — the two text serializations.
- [x] **`_sc` namespaced render dirs** at root + render banner.
- [x] **Drop directory-as-state** for roadmap status (DB column).
- [x] **Onboarding mapper + backfill skill** (dr_* generalized); ingest is one-time only.
- [x] **Dual-render boot** (`AGENTS.md` + `CLAUDE.md`) + skills as `.claude/skills/*/SKILL.md` — near-universal across harnesses.
- [x] **OpenCode = adapter #2**; contract drafted from research (build-time verify items noted).
- [x] **v1 harness targets = Claude Code + OpenCode**; Goose/Crush/gptme additive, not v1.
- [x] **GUI ships in v1** as a review layer (shells / roadmap / flags); schema multi-user, front end single-user.
- [x] **Feature : many specs**, each individually freezable (`frozen` field, not folder).

### Still open

- [ ] Maintainer shell lineage (succession / clone / fresh).
- [ ] Commit→PR concurrency model for parallel shells.
- [ ] GUI edit policy — confirm L&S is shell-curated (read-only in GUI) vs FnB-editable.

### Related work (other repos)

- [x] **md-converter open-in-mdc:** use the existing `?c=` inline deep-link — no md-converter change; reuse the Python encoder.
- [ ] **md-converter** also becomes a super-coder fork target.
', 'specs_sc/super-coder-founding-spec.md', '2026-06-04 10:30:53', '2026-06-04 10:30:53');
INSERT INTO documents (document_id, feature_id, kind, seq, title, frozen, frozen_date, body, render_path, created_at, updated_at) VALUES (2, 8, 'spec', 1, 'B5 — Repo Navigation: Sections, Descriptions & CONNECTIONS', 0, NULL, '---
title: B5 — Repo Navigation — Sections, Descriptions & the CONNECTIONS Block
tags: [super-coder, spec, B5, mapping, navigation, cartographer, render]
date: 2026-06-06
project: super-coder
purpose: Give every shell a cheap, accurate answer to "where does this live?" — a sectioned, described repo map surfaced through a single CONNECTIONS block.
---

# B5 — Repo Navigation: Sections, Descriptions & the CONNECTIONS Block

> Stage spec for **B5 — Onboarding & mapping**. The base `dr_*` map (files /
> deps / env, `./sc map`, the `surface_catalogue` skill) is shipped. This stage
> builds the *navigation layer* on top of it and fixes how the boot doc orients a
> shell about where things live. Supersedes the old "semantic tables
> (api/db/page)" line in the B5 summary.

## Overview

A QAQC of the boot render (render → compose → flat → prompt) surfaced one real
failure mode behind "shells get confused about where things are," plus three
contributing gaps:

1. **`connections` is a dead column.** `schema.sql` defines `shells.connections`;
   `shell_factory` collects it; `compose.py` **never renders it** (it renders
   `workspace` only). Verified empty on every live shell. A column literally
   named "where things live" is stored and shown to no one.
2. **`workspace` and `connections` are the same concept** — "where things live" —
   but only `workspace` is rendered, and it is thin free-text.
3. **The repo map is surfaced as a number, not a pointer.** `compose.py` reads
   `dr_filepath`/`dr_repo` and renders only counts into `## STATUS`. The actual
   "where things live" knowledge sits in `dr_filepath` and is reachable only if
   the shell elects to run `surface_catalogue`. The FIRST-RUN block tells a fresh
   shell *how* to read the map; that nudge vanishes once `bootstrapped=1`, leaving
   a returning shell with a count and no standing instruction.
4. **The docs count is misleading.** `## STATUS` shows `N ingested / M in repo`,
   where `M` counts *all* host-repo markdown (READMEs, PR/issue templates,
   CHANGELOG, and — in substrate-containing forks — embedded substrate assets).
   It can never reconcile with `documents` (only things ingested via `onboard`),
   so it always reads as a false "un-ingested" backlog.

The fix is a single **`## CONNECTIONS`** block that replaces `## WORKSPACE`,
backed by a **sectioned, described** view of the repo map. The shell sees *where
to start* at boot (UI here, API here, docs here) and queries *the leaves* (file
names + descriptions) only inside the one section it picked — one cheap query
deep, never a full preload.

## Goals

- A returning (already-bootstrapped) shell can answer "where does X live?" from
  the boot doc + one scoped query — without grepping blind or reading wrong files.
- One surface for "where things live." No dead column, no redundant pair.
- Per-file descriptions exist and are *curated* (single owner: the cartographer),
  never invented at render time, and survive the auto-remap that working shells
  trigger.
- Boot cost stays bounded and cache-stable; description detail is paid only on
  demand, inside a chosen section.

## Non-goals

- Typed semantic tables (`dr_api` / `dr_db` / `dr_page`). `dr_section` is the
  general navigational layer and replaces that deferred pass. Revisit only if a
  concrete need appears.
- Changing the base mapper''s file/dep/env extraction. This stage layers on top.
- Auto-generating descriptions with an ad-hoc LLM call. Descriptions are
  cartographer-authored content, not a render-time inference.

## Background — the current chain

```
DB (shell_db.db, gitignored cache; rebuilt from schema.sql + migrations/ + snapshot/content.sql)
  → compose.py :: compose_boot()   assembles the boot markdown
  → run.py                         dual-writes CLAUDE.md + AGENTS.md, exec''s the harness
dr_* map (separate): map_repo.py walks the host repo → dr_filepath / dr_dependency / dr_env / dr_repo
```

Key current facts this stage changes:
- `compose.py` renders `## WORKSPACE` from `shells.workspace`; `connections` is
  never read.
- `map_repo.py` does `DELETE FROM dr_filepath` then re-INSERTs on **every** run,
  and the git `post-checkout` hook runs it automatically (working shells, not the
  cartographer). Any authored column on `dr_filepath` is therefore destroyed on
  the next checkout unless explicitly preserved.
- `dr_filepath` columns today: `path, ext, lang, role, bytes, lines`. No
  description, no section.

## Design

### 1. `## CONNECTIONS` replaces `## WORKSPACE`

One block, three layers, top to bottom:

1. **Derived header** (rendered from facts, never authored):
   - "Need to find something? Look here first." → `surface_catalogue` /
     `dr_filepath`.
   - Repo root + branch + `mapped_at` (from `dr_repo`).
   - Shared-folder path: `<repo_root>/shared` (see §6).
2. **Section index** — the navigational core (from `dr_section`): one line per
   section — `name · location · file-count · one-line description`. This is the
   "UI here / API here / docs here" list.
3. **Authored notes** — the free-text `connections` column: wiring, services,
   deploy facts the map cannot derive ("prod deploys from `main` via CF Pages";
   "email OAuth spans these three files").

`shells.workspace` is dropped. Any existing workspace text migrates into the
authored `connections` notes layer.

**Division of responsibility (single source of truth):** the map owns raw paths;
`connections` notes own *meaning the map cannot derive*. Do not hand-author file
paths into the notes — that re-creates drift the section index already prevents.

### 2. `dr_section` — sectioned navigation (new table)

Authored, stable, small (~10–20 rows). **Not wiped** by the remap.

```sql
CREATE TABLE dr_section (
    section_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name         TEXT NOT NULL,          -- "API", "UI", "Docs", "Schema", …
    path_prefix  TEXT NOT NULL,          -- repo-relative prefix or glob the section covers
    description  TEXT,                    -- one line, what this area is
    sort_order   INTEGER NOT NULL DEFAULT 0,
    UNIQUE(name)
);
```

- Files join to a section **by path-prefix at query/render time** — `dr_section`
  stores no file IDs, so it never needs re-stitching when `dr_filepath` is wiped
  and repopulated. A new file the hook adds **auto-falls into its section** by
  path.
- **Seeded** from top-level directories on first map (non-empty index on day
  one); the cartographer renames / merges / re-describes (e.g. seed gives
  `shell_core` → cartographer splits into `API: shell_core/api`, `UI:
  shell_core/ui`).
- **Catch-all:** files matching no section render under an **"other /
  unsectioned"** bucket — never hidden. That bucket is the cartographer''s
  worklist ("a new area appeared; section it").

### 3. `dr_filepath.desc` — per-file descriptions

```sql
ALTER TABLE dr_filepath ADD COLUMN desc TEXT;   -- ≤100 chars, cartographer-authored
```

- Authored by the cartographer; `NULL` until described.
- **Never bulk-loaded at boot.** Queried only *within a chosen section*, via
  `surface_catalogue`. The boot doc carries the section index; the descriptions
  are the leaves the shell reaches for after it has narrowed to one section.

### 4. Surviving the auto-remap wipe (the core mechanic)

This is the make-or-break. `map_repo.py` must stop destroying authored content:

- Replace `DELETE FROM dr_filepath` + blind re-INSERT with an **UPSERT keyed by
  `path`** that **preserves `desc`** for paths whose content is unchanged.
- New or changed paths land with `desc = NULL`.
- Paths that disappeared from the repo are deleted (their `desc` goes with them —
  correct).
- `dr_section` is untouched by the mapper (authored content; the cartographer
  owns it). Section membership is recomputed for free by the prefix join.

Result: the automatic hook (working shells) keeps the file list fresh; authored
descriptions and sections persist; the cartographer fills gaps on its own cadence
and **never blocks the hook**.

**Worklists (queryable):**
- Undescribed files: `SELECT path FROM dr_filepath WHERE desc IS NULL ORDER BY role, path;`
- Unsectioned files: files whose path matches no `dr_section.path_prefix`.

### 5. Render: the section index, not the leaves

`compose.py` renders the section index (layer 2 above) — bounded by construction
(~10–20 sections), so boot cost is small and **cache-stable** (changes only when
sections change, not when files churn). Per-file descriptions are deliberately
*not* rendered at boot. The shell flow:

> need a doc → CONNECTIONS shows `Docs → docs_sc/, *.md` → query that section''s
> leaves → read one or two descriptions → open the right file.

Knows where to start and what to look for, without loading it all at the top.

### 6. Shared folder

`install` creates `<repo_root>/shared/` (a host-repo scratch/handoff dir). The
CONNECTIONS derived header states the path. Derived by convention (relative to
repo root) — not stored in a column.

### 7. Docs-count fix

Narrow the `## STATUS` docs denominator to *ingestable host-repo docs*:
- Exclude engine paths (already `.super-coder/%`) **and** embedded substrate
  assets in substrate-containing forks.
- Exclude non-ingestable markdown (PR/issue templates, CHANGELOG, license-style
  files) — or reframe the line so it does not imply "ingest all of these."

Goal: the ratio stops reading as a false "un-ingested" backlog.

### 8. Cartographer — two standing jobs

The cartographer flavor + skill gain explicit ownership of:
1. `dr_section` — author/curate sections (seed-refine), keep the catch-all empty.
2. `dr_filepath.desc` — fill descriptions, worklist-driven (`desc IS NULL`).

Both are best-effort and NULL-until-curated; neither blocks the auto-remap hook
that working shells trigger.

## Change surface (all engine-side, in the super-coder source repo)

| File | Change |
|---|---|
| `schema.sql` | add `dr_section`; add `dr_filepath.desc`; drop `shells.workspace` |
| `migrations/NNNN_*.sql` | additive migration for installed forks (new table + column; workspace handled per "Migration" below) |
| `scripts/map_repo.py` | DELETE+INSERT → UPSERT preserving `desc`; seed `dr_section` from top-level dirs |
| `render/compose.py` | `## CONNECTIONS` (header + section index + authored notes); drop `## WORKSPACE`; fix docs-count denominator |
| `scripts/install.py` | create `<repo_root>/shared/` |
| `assets/shells/cartographer.*` / cartographer SKILL | add the two jobs + worklist queries |
| `snapshot/content.sql` | regenerated via `./sc snapshot` (shell content: connections notes, sections) |
| reseed migration | so already-installed forks pick up the schema + cartographer-asset changes |

## Migration & fork reseed

- New table + new column are additive — straightforward forward migration.
- Dropping `shells.workspace`: SQLite requires table-rebuild for a true `DROP
  COLUMN` (or leave the column unused and stop rendering it). Decide at
  implementation time; leaving it unrendered is the lower-risk path and can be
  cleaned up later.
- The cartographer asset/skill edits need a **reseed migration** (the
  asset-content sync path) so existing forks pick up the new behavior on
  `./sc update`, not just fresh installs.
- This is engine work, done in the super-coder source repo — never patched into a
  fork''s `.super-coder/` directly (a fork''s engine is checkout-scoped on update;
  in-place edits are clobbered or silently diverge).

## Token economics (why this shape)

- The boot doc is the system prompt — **prompt-cached** and stable between map
  changes. A bounded section index is one cheap cache-stable cost.
- Per-file descriptions, if preloaded, would be a large recurring cost (hundreds
  of files × ~25 tokens) and would churn the cache on every auto-remap. Querying
  them inside a chosen section pays detail cost only when needed.
- Wrong-file reads are *uncacheable churn* (fresh tokens every time + polluted
  context). The section index + on-demand descriptions trade a small stable boot
  cost for fewer wrong reads — net win over a session.

## Decisions settled

- **CONNECTIONS replaces WORKSPACE** — one "where things live" surface; the dead
  `connections` column gets a render; `workspace` retired.
- **`dr_section` (general, authored) over typed semantic tables** — defer
  `dr_api`/`dr_db`/`dr_page`.
- **Descriptions are cartographer-authored and preserved across remap** — not
  render-time inference, not wiped by the hook.
- **Render the section index, not the leaves** — boot loads where-to-start;
  descriptions are queried on demand inside a section.
- **Sections are seeded from top-level dirs, then curated** — non-empty on day
  one; catch-all bucket keeps the index complete.

## Open questions

- Exact `dr_section` seeding heuristic (top-level dirs only, or first two levels
  for nested layouts like `shell_core/{api,ui}`?).
- Whether to surface an undescribed/unsectioned count in `## STATUS` to ping the
  cartographer sooner (vs. leaving it as a quiet worklist).
- Whether to true-`DROP` `workspace` (table rebuild) now or leave it unrendered
  and clean up in a later structural pass.

## Out of scope (later)

- Typed semantic tables (`dr_api`/`dr_db`/`dr_page`).
- Semantic descriptions of *symbols* (functions/classes) — this stage is
  file-level.
- Cross-repo sections (multi-repo shells) — current model is one shell, one repo.
', 'specs_sc/b5-repo-navigation.md', '2026-06-05 23:27:12', '2026-06-05 23:27:12');
INSERT INTO documents (document_id, feature_id, kind, seq, title, frozen, frozen_date, body, render_path, created_at, updated_at) VALUES (3, 10, 'spec', 1, 'B7 — Engine/Fork Separation & Update Lifecycle', 0, NULL, '---
title: B7 — Engine / Fork Separation & Update Lifecycle
tags: [super-coder, spec, B7, fork, engine, update, rollback, migrations, lifecycle]
date: 2026-06-07
project: super-coder
purpose: Make a fork treat the engine as a gitignored downstream dependency and its DB as the one preserved artifact — so shells stop confusing the substrate for the project, and updates become snapshot→migrate with a sound rollback.
---

# B7 — Engine / Fork Separation & Update Lifecycle

> Stage spec for a new pillar. Forks are **downstream variants**: all change
> flows *down* from the super-coder source repo, nothing flows back up. The only
> per-fork artifact that must survive is the fork''s **DB (its memory)**. This
> spec stops a fork''s shells from mistaking the engine for the project, and
> defines a snapshot→migrate→rollback update lifecycle around the DB.

## Overview

Shells in a fork keep referencing the super-coder engine''s DB and `schema.sql`
instead of the host repo they are meant to build — they confuse the **substrate
they run on** with the **project they work on**. A QAQC of the boot + git
surfaces found the cause is *not* where the boot artifact renders (it already
renders at the host root and boots with `cwd` = host root). It is two things:

1. **The engine is committed into the host repo.** A fork vendors ~60+ engine
   files under `.super-coder/` into its own git history. `git status` / `git log`
   / `git diff` — a shell''s primary "what am I working on" signal — surface
   engine churn mixed with project work, and the engine tree (`schema.sql`,
   `run.py`, `api/`, `ui/`) reads as a codebase to edit.
2. **Nothing draws the project/engine line.** The boot doc leads with
   engine-memory pointers (`.super-coder/shell_db.db`, `schema.sql`) and never
   says, on the always-loaded path, "this repo is your project; `.super-coder/`
   is the engine you run on, not your code."

The fix follows from the downstream-variant model. If updates only ever flow
down and nothing flows up, the engine is a **dependency**, not fork-owned
source — so it should be **gitignored and materialized from upstream**, exactly
like `node_modules/` or `.venv/`. That single move also *is* the conceptual fix:
a shell treats a gitignored `.super-coder/` as not-its-project automatically,
the same way it already ignores `node_modules/`. The one thing a fork must
preserve — its DB — is then handled by an explicit `make update` (snapshot →
migrate) and `make rollback` (restore) lifecycle.

## Goals

- A fork''s git surfaces show **only the project**, never engine churn.
- The engine is a **materialized dependency** pinned to an upstream ref, not
  vendored source in the fork''s history.
- The fork''s **DB/memory is the one preserved artifact**, with a durable
  git-tracked serialization and an ephemeral pre-update restore point.
- `make update` = snapshot → migrate, automatically and safely (it largely
  exists already in `./sc update`).
- `make rollback` = a **sound** undo of a bad update — restoring the DB *and*
  the engine version together, because engine code is read live.
- One always-loaded line in the boot doc that names the project/engine split.

## Non-goals

- Per-step down-migrations (reversible `up()`/`down()` SQL). Rollback is a
  whole-restore, not a schema-reversal — see *Decisions settled*.
- Any upstream flow from forks (PRs, contributions back to super-coder). Forks
  are variants; engine changes are authored in the source repo only.
- A submodule for the engine (evaluated and dropped — see *Decisions settled*).
- Changing where the boot artifact renders or what `cwd` a shell boots in —
  both are already correct.

## Background — the current chain

What already works and must be preserved:

- **Boot artifact location.** `CLAUDE.md` / `AGENTS.md` / `opencode.json` render
  at the **host repo root** and are already gitignored. `./sc boot` execs the
  harness with `cwd` = repo root (`-w "$here"`). The engine lives in
  `.super-coder/`.
- **DB is derived, text is canonical.** `.super-coder/shell_db.db` is gitignored
  and rebuilt from `schema.sql` + `migrations/` + `snapshot/content.sql`.
  `snapshot/content.sql` (per-instance tables dumped by `./sc snapshot`) is the
  git-tracked source of truth for a fork''s memory.
- **Update is already snapshot-then-migrate.** `./sc update` (update.py):
  (1) fetch + `git checkout super-coder/<branch> -- <ENGINE_PATHS>`,
  (2) `rebuild.backup_existing()` → timestamped binary copy
  `shell_db.prerebuild.<ts>.db` (restore point),
  (3) migrate **in place**, ledger-tracked (only un-applied migrations; all rows
  preserved), (4) sync skills catalogue (id-stable UPSERT), (5) re-grant common
  skills, (6) wire hooks + map + snapshot.
- **Migrations are the propagation channel.** New skills, boot-render changes,
  schema changes all arrive as migrations + a skills-seed sync.

What is wrong:

- The engine is **git-tracked in the fork** (the update channel is implemented as
  a `git checkout` into the same tree, which assumes tracked paths). This is the
  root of the confusion and the history pollution.
- **Per-fork state lives *inside* the engine dir** — `snapshot/content.sql` (the
  DB source of truth) and `map.config.json` (per-fork cartographer tuning) sit
  under `.super-coder/`. They only "need the engine tracked" because of where
  they happen to live.

## Design

### 1. Mental model: the engine is a dependency

`.super-coder/` is a **materialized runtime dependency**, not fork source. It is
fetched from the super-coder upstream at install, refreshed on update, and never
committed to the fork. The fork commits *what it owns* — its project, plus its
own memory serialization and a pin recording which engine version it runs.

### 2. Relocate per-fork state out of the engine dir

Move fork-owned, must-persist state out of `.super-coder/` into a host-tracked
state dir (proposed `.sc-state/`):

| Moves to `.sc-state/` (git-tracked) | Stays in `.super-coder/` (gitignored) |
|---|---|
| `content.sql` — the DB serialization (memory) | `shell_db.db*` — live DB (derived) |
| `map.config.json` — per-fork map tuning | `schema.sql`, `migrations/`, `scripts/`, `api/`, `ui/`, `templates/`, `adapters/`, `render/`, `hooks/`, `assets/skills/` — engine |
| `engine.ref` — the engine version pin (new) | `instance.json` — derived ports (already gitignored) |

This relocation is the one real cost, and it is **required by any** engine/fork
separation (submodule or gitignore alike): a fork''s memory cannot live inside a
dir that is replaced wholesale from upstream. Path references update in
`run.py`, `rebuild.py`, `snapshot.py`, `update.py` (and anywhere else
`snapshot/content.sql` / `map.config.json` are named).

### 3. The engine pin — `.sc-state/engine.ref`

A tiny tracked file recording the upstream commit SHA the fork is materialized
at. Written by `make update` after a successful fetch. It is (a) the fork''s
version record and (b) the engine half of a sound rollback (§6). One SHA, not a
vendored tree.

### 4. Gitignore the engine

Add `/.super-coder/` to the fork''s `.gitignore` (keeping the existing explicit
ignores for the live DB redundant-but-harmless). The tracked bootstrap surface
the fork keeps is only: `sc` (the dispatcher), the `Makefile`, `.gitignore`, and
`.sc-state/` (memory + pin). `./sc install` materializes `.super-coder/` from
upstream on a fresh clone; `make update` keeps it current.

### 5. `make update` — snapshot → migrate (mostly exists)

`make update` → `./sc update`, rewritten so the engine arrives by **fetch +
materialize into the gitignored dir** (copy from a fetched ref) instead of
`git checkout -- <paths>` + commit. Flow:

1. Capture a **restore point** (§6): `backup_existing()` DB copy **+** record the
   *current* `engine.ref` as `engine.ref.prev`.
2. Fetch upstream; materialize `.super-coder/` at the new ref; write the new
   `engine.ref`.
3. Migrate in place (ledger-tracked) — unchanged.
4. Sync skills, re-grant, map, snapshot — unchanged.

No commit step for the engine (it is ignored). The fork commits only `.sc-state/`
changes (refreshed `content.sql` + bumped `engine.ref`).

### 6. `make rollback` — a *sound* pair-restore (new)

The subtlety: **engine code is read live every session**, and a migration exists
*because new code expects the new schema*. Restoring only the DB would leave new
engine code running against the old schema. So a restore point is a **pair** and
rollback restores both:

`make rollback` → `./sc rollback`:

1. Back up the *current* (post-bad-update) DB first, so rollback is itself
   reversible — you can never lose state by rolling back.
2. Restore the DB from the most recent `shell_db.prerebuild.<ts>.db`.
3. Re-materialize the engine at `engine.ref.prev`; restore `engine.ref`.
4. Checkpoint/clear `-wal`/`-shm`.

Whole-restore, not down-migration. The only data lost is anything written
*between* the update and the rollback — a seconds-wide window in practice
("migrated, it broke, rolled back").

### 7. Boot doc — the always-loaded project/engine line

One short block near the top of `templates/boot.md` (a render-chain edit, gated
on owner OK):

> **Your project is this repo** — everything except `.super-coder/`.
> `.super-coder/` is the **engine** you run on (your memory + identity
> substrate), a gitignored dependency — do not treat it as the project or edit
> it. Engine changes are authored upstream in super-coder, never here.

Plus a one-line guardrail in the `git-workflow` skill: operate on the project,
never the engine.

## Change surface (all engine-side, in the super-coder source repo)

- `rebuild.py`, `snapshot.py`, `run.py`, `update.py` — repoint `content.sql` and
  `map.config.json` to `.sc-state/`; add `engine.ref` read/write.
- `update.py` — swap the engine `git checkout` for fetch-and-materialize; capture
  `engine.ref.prev`; write `engine.ref`.
- New `scripts/rollback.py` — pair-restore (DB backup + engine ref).
- `sc` — add `rollback` dispatch; keep `update` (now materialize-based).
- `Makefile` (fork-facing) — `update` and `rollback` targets wrapping `./sc`.
- `.gitignore` (fork template) — ignore `/.super-coder/`.
- `install.py` — materialize `.super-coder/` from upstream on fresh clone;
  initialize `.sc-state/`.
- `templates/boot.md` — project/engine block (**owner-gated render-chain edit**).
- `git-workflow` skill — one-line guardrail.

## Migration & fork reseed

- **State relocation migration**: move `snapshot/content.sql` →
  `.sc-state/content.sql` and `map.config.json` → `.sc-state/map.config.json` on
  first `make update` after this ships; leave a one-release shim that reads the
  old path if the new is absent.
- **Engine untrack**: `git rm -r --cached .super-coder` in a fork once, then the
  new `.gitignore` keeps it out. The working tree is untouched (files stay; only
  git stops tracking them).
- **Proving ground**: land it on the super-coder source repo, then exercise the
  full `make update` / `make rollback` cycle on the **dos-arch** fork before
  calling it done (it carries a legacy substrate too — the sharpest test of "is
  the project clearly the project").

## Decisions settled

- **Gitignore the engine, not submodule it.** Submodule adds ceremony (detached
  HEAD, `--recursive` clones, gitlink churn) and still requires the same state
  relocation. The dependency/gitignore model is simpler *and* self-documents the
  project/engine split.
- **Engine is tracked nowhere in the fork.** The only reasons to track it
  (update channel, memory persistence, version pin, local edits) are each
  satisfied without it: update → fetch/materialize; memory → `.sc-state/`;
  version → `engine.ref`; local edits → not allowed (forks are downstream).
- **Rollback = whole-restore, not down-migrations.** Zero reverse-SQL to author,
  never surprisingly lossy, always works. Down-migrations are a maintenance tax
  and lossy on column drops — overkill for a single-writer fork DB.
- **Rollback restores the (DB + engine) pair.** Because engine code is live,
  DB-only rollback yields new-code-on-old-schema. The `engine.ref.prev` pin is
  what makes rollback sound.
- **Two preservation artifacts, distinct jobs.** `.sc-state/content.sql` (text,
  tracked) = preserve the fork forever (portable, diffable, survives a fresh
  clone). `shell_db.prerebuild.<ts>.db` (binary, ignored) = undo this one update.

## Open questions

- State dir name/location: `.sc-state/` vs folding into an existing tracked dir.
- Backup retention: how many `prerebuild.*.db` to keep before pruning.
- Should `make update` auto-rollback on a migration *failure* (vs leaving it for
  a manual `make rollback`)? Default here is manual; auto-on-failure is a small
  add.
- Fresh-clone bootstrap UX: does `make update` imply `./sc install` when
  `.super-coder/` is absent, or stay separate verbs?

## Out of scope (later)

- Multi-engine / pinned-channel forks (a fork tracking a non-`main` engine line).
- Signed/verified engine fetches.
- A `make doctor` check that the engine ref matches what migrations expect.
', 'specs_sc/b7-engine-fork-separation.md', '2026-06-07 13:25:16', '2026-06-07 13:25:16');
INSERT INTO documents (document_id, feature_id, kind, seq, title, frozen, frozen_date, body, render_path, created_at, updated_at) VALUES (4, 11, 'spec', 1, 'Dev shell git worktrees — implementation spec', 1, '2026-06-11', '# Dev shell git worktrees

## Problem

Multiple dev shells sharing one git tree clobber each other — one shell''s
`git checkout` or `git restore` undoes another shell''s uncommitted work. The
fix is structural: each dev shell owns its own worktree.

## Solution

Use `git worktree` — same repo, multiple checked-out branches, separate
directories. Lightweight: shared object store, no clone overhead.

## Path convention

`<parent>/<repo>-<shortname_lower>/`
e.g. `~/dos-arch-dev1/`, `~/dos-arch-dev2/`

## Surfaces to change

### 1. Schema — `0013_dev_worktrees.sql`
ADD COLUMN `worktree_path TEXT` to `shells`. Nullable — only dev shells get it.

### 2. `shell_factory.py`
After inserting a dev shell:
```python
worktree_path = REPO_ROOT.parent / f"{REPO_ROOT.name}-{shortname.lower()}"
subprocess.run(["git", "-C", str(REPO_ROOT), "worktree", "add",
                str(worktree_path)], check=True)
con.execute("UPDATE shells SET worktree_path=? WHERE shell_id=?",
            (str(worktree_path), shell_id))
```
Non-dev flavors: skip. Branch: start on main, let the shell branch when it
picks up work.

### 3. `run.py` (launcher)
Read `worktree_path` from the shells row at launch. If set, cd into it before
exec''ing claude. The shell''s cwd IS its tree.

### 4. Boot template (`shell_system_prompt.md` / `boot.md`)
Render `worktree_path` in the WORKSPACE block for dev shells:
`Worktree: <path>  (main repo object store: <REPO_ROOT>)`

### 5. `git` skill
Add: "Dev shells operate from their worktree (`shells.worktree_path`). All git
work runs there. The main repo root is the object store only — do not cd into
it for day-to-day work."

### 6. Shell deletion cleanup
Wherever shell deletion is handled, add:
```bash
git -C <REPO_ROOT> worktree remove <worktree_path> --force
git -C <REPO_ROOT> worktree prune
```

## Out of scope (this spec)

- Reviewer/planner worktrees — they are git read-only; shared tree is fine
- `./sc worktree-list` command — nice to have, not needed for v1
- snapshot.py changes — snapshots are DB-level, not tree-level; no change needed

## Done condition

A new dev shell created via `./sc init` or the GUI has a worktree at the
expected path. Launching that shell opens claude with cwd = worktree path.
Two dev shells can be launched simultaneously on different branches without
touching each other''s uncommitted work.', 'specs_sc/dev-worktrees.md', '2026-06-11 00:15:53', '2026-06-11 00:15:53');

DELETE FROM flags;
INSERT INTO flags (flag_id, display_name, priority, description, created_date, resolved_date, resolved, shell_id, feature_id, resolution_notes, parent_flag_id, is_deleted) VALUES (1, 'SC-001', 'Low', '[Test] review layer smoke flag | Blocker for: nothing', '2026-06-04', '2026-06-04', 1, NULL, 1, 'smoke test done', NULL, 0);

DELETE FROM projects;
INSERT INTO projects (project_id, shortname, title, purpose, standing, status, is_deleted, created_at) VALUES (1, 'super-coder', 'super-coder', 'Forkable shell substrate for a single repo — DB-backed identity, memory, roadmap, content; harness-agnostic boot.', NULL, 'active', 0, '2026-06-04 10:30:53');

DELETE FROM project_shells;
INSERT INTO project_shells (project_shell_id, project_id, shell_id, role, added_date, is_deleted) VALUES (1, 1, 1, 'maintainer', '2026-06-04', 0);

-- Project-local skills only. Engine-seeded skills come from migrations.
DELETE FROM skills WHERE name NOT IN ('api-design', 'blueprint', 'bootstrap', 'cartographer', 'database-migrations', 'db_map', 'dev_kit', 'docs', 'flags', 'git', 'local_skill_management', 'memory', 'messaging', 'migration_management', 'onboard', 'redline_review', 'self_update', 'snapshot', 'spec', 'surface_catalogue', 'test_authoring');

DELETE FROM shell_skills;
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='api-design';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='blueprint';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='bootstrap';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='database-migrations';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='db_map';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='docs';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='flags';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='git';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='memory';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='messaging';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='onboard';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='self_update';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='snapshot';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 1, skill_id FROM skills WHERE name='surface_catalogue';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='bootstrap';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='cartographer';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='db_map';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='git';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='memory';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='messaging';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='self_update';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='snapshot';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 2, skill_id FROM skills WHERE name='surface_catalogue';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='bootstrap';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='database-migrations';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='db_map';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='dev_kit';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='docs';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='flags';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='git';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='memory';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='messaging';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='redline_review';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='self_update';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='snapshot';
INSERT INTO shell_skills (shell_id, skill_id) SELECT 3, skill_id FROM skills WHERE name='surface_catalogue';

DELETE FROM shell_messages;

DELETE FROM dr_section;
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (2, '.super-coder', '.super-coder/', NULL, 0);

COMMIT;
