-- super-coder MAP authored layer — GENERATED by scripts/snapshot.py.
-- The cartographer-curated sections of the map DB (.sc-state/map.db).
-- Idempotent; reloaded into a fresh map DB by map_db.seed_authored().
-- The rest of the map (files/deps/env) is a derived cache — re-mapped,
-- not snapshotted. Do not hand-edit — curate via the shell, then snapshot.

BEGIN;

DELETE FROM dr_section;
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (1, '.super-coder', '.super-coder/', NULL, 0);

COMMIT;
