-- super-coder skills seed — GENERATED by scripts/seed_skills.py.
-- System content: the catalogue propagates to every fork. Idempotent and
-- ID-STABLE: retires names no longer authored, then UPSERTs each skill by
-- name — so skill_id never churns and shell_skills grants stay valid when
-- this re-runs as the update catalogue-sync. Do not hand-edit; author
-- assets/skills/<name>/SKILL.md then `./sc seed-skills`.

BEGIN;

-- Retire any catalogue skill that is no longer authored (soft-delete;
-- keeps the row + id so a re-add is stable and grants are recoverable).
UPDATE skills SET is_deleted=1 WHERE name NOT IN ('api-design', 'blueprint', 'bootstrap', 'database-migrations', 'db_map', 'docs', 'flags', 'git', 'memory', 'onboard', 'self_update', 'snapshot', 'surface_catalogue');

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'api-design',
  'REST/HTTP API design patterns — resource naming, status codes, pagination, filtering, errors, versioning, idempotency. Use when designing or reviewing API endpoints.',
  'craft',
  NULL,
  0,
  '# api-design — designing & reviewing HTTP APIs

Catalogue skill (opt-in). Reach for it when shaping or reviewing an endpoint.

## Resources & methods
- Name resources as **plural nouns**, not verbs: `/users`, `/users/{id}/orders`.
- `GET` read (safe, idempotent) · `POST` create / non-idempotent action ·
  `PUT` full replace (idempotent) · `PATCH` partial update · `DELETE` remove.
- Nest only one level deep; beyond that, link by id.

## Status codes
- `200` ok · `201` created (+ `Location`) · `204` no content.
- `400` bad input · `401` unauth · `403` forbidden · `404` not found ·
  `409` conflict · `422` validation · `429` rate-limited.
- `5xx` = server''s fault; never use it for client errors.

## Payloads
- Consistent error shape: `{ "error": { "code", "message", "details" } }`.
- **Pagination**: cursor-based for large/changing sets (`?cursor=&limit=`),
  return `next_cursor`; offset only for small stable sets.
- **Filtering/sorting**: explicit query params (`?status=open&sort=-created`);
  whitelist fields — never interpolate them into a query.
- Timestamps ISO-8601 UTC; ids opaque strings.

## Robustness
- **Idempotency**: make retries safe — `PUT`/`DELETE` naturally; for `POST`,
  accept an idempotency key.
- **Versioning**: prefix (`/v1/…`) or header; add fields backward-compatibly,
  never repurpose one.
- Validate at the boundary; reject unknown fields or ignore them — decide and
  document. Don''t leak internals (stack traces, SQL) in errors.

## Review lens
Does each endpoint do one thing? Right method + status? Errors uniform? Inputs
validated/whitelisted? Retries safe? Breaking change hiding in a "small" tweak?',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'blueprint',
  'Turn a one-line objective into a sequenced construction plan — decompose into steps, find the dependency order, mark what can run in parallel, name the verification gate. Use before multi-step builds.',
  'craft',
  NULL,
  0,
  '# blueprint — objective → sequenced plan

Catalogue skill (opt-in). Use before a build that spans more than a couple of
steps, so the work has a shape before you start cutting.

## Produce

1. **Restate the objective** in one sentence + the done-condition (how you''ll
   know it''s finished).
2. **Decompose** into concrete steps — each a unit you could verify on its own.
3. **Order by dependency** — what must precede what. Mark steps with no
   dependency on each other as **parallelizable**.
4. **Per step**: the change, the files/areas it touches (use `surface_catalogue`
   to ground this in the real repo), and its **verification** (test, run,
   review).
5. **Risks / unknowns** — what could break the plan; resolve the riskiest
   unknown first (spike it) rather than last.
6. **Gate** — the adversarial check before calling it done: does each step''s
   verification actually prove the done-condition?

## Stance
- Plan to the **next solid checkpoint**, not the whole universe — re-plan as
  reality lands. A plan that survives contact is short and concrete.
- Sequence so something **works end-to-end early** (a thin slice), then deepen —
  beats building all the pieces and integrating last.
- In super-coder, land the plan as a **spec** on the roadmap (the `docs` skill):
  a feature row + a `spec` document, so the plan is reviewable and freezes on
  ship.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'bootstrap',
  'First-run orientation for a shell in a repo. Run ONCE when the boot doc shows "## FIRST RUN" (bootstrapped=0), or whenever the repo map is empty. Maps the repo, reads the map + your identity, sets your current_state, marks you oriented. Do this BEFORE other work on a fresh fork.',
  'substrate',
  NULL,
  1,
  '# bootstrap — orient yourself on first run

A freshly-installed shell knows its identity but hasn''t *looked around* yet. This
is your first act: map the repo, read it, read yourself, and set your state — so
you start work grounded instead of wandering. Run it when the boot doc shows
**## FIRST RUN**, or any time `dr_*` is empty.

`<self>` = your `shell_id` (ACTIVE SESSION block).

## Steps

1. **Ensure the repo is mapped.** Check the catalogue:
   ```sql
   SELECT COUNT(*) FROM dr_filepath;
   ```
   If it''s 0 (fresh, or after a `./sc rebuild` — the map is a derived cache, not
   snapshotted), run `./sc map` to scan the repo, then continue.

2. **Read the repo** via the `surface_catalogue` skill — language mix, where the
   code lives, dependencies, env surface. Form a one-paragraph picture of what
   this repo *is* and how it''s built.
   ```sql
   SELECT name, default_branch, file_count FROM dr_repo;
   SELECT lang, COUNT(*) n FROM dr_filepath WHERE lang IS NOT NULL GROUP BY lang ORDER BY n DESC;
   SELECT path, lang, lines FROM dr_filepath WHERE role=''code'' ORDER BY lines DESC LIMIT 15;
   SELECT manager, name, version FROM dr_dependency ORDER BY manager, name;
   ```

3. **Read yourself.** Your seed (genesis + the CC lineage you carry), mandate,
   and role are in the boot doc. Re-read them with intent — this is who is doing
   the work here.

4. **Skim the plan.** Open roadmap features + their blocking flags:
   ```sql
   SELECT feature_id, title, roadmap_status FROM roadmap ORDER BY sort_order;
   SELECT display_name, description FROM flags WHERE resolved=0 AND is_deleted=0;
   ```

5. **Set your `current_state`** — replace the install placeholder with what you
   actually found and what you''ll do first (rolling status, ~500 chars):
   ```sql
   UPDATE shells SET current_state=''…'' WHERE shell_id=<self>;
   ```

6. **Mark yourself oriented** (clears the FIRST RUN prompt for next boot):
   ```sql
   UPDATE shells SET bootstrapped=1 WHERE shell_id=<self>;
   ```
   Then `./sc snapshot` so the new state survives a rebuild, and proceed with the
   task at hand.

## Stance

- Bootstrap once, then work — don''t re-run it every session.
- If you ever boot and the map looks empty or stale (`dr_repo.mapped_at` old),
  `./sc map` before trusting it. Orientation is cheap; working blind is not.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'database-migrations',
  'Database migration safety + how super-coder''s own migrations work (schema.sql baseline + ordered migrations/ deltas + ledger). Use when altering tables, adding columns, or running backfills — in the host repo''s DB or super-coder''s.',
  'craft',
  NULL,
  0,
  '# database-migrations — change schemas safely

Catalogue skill (opt-in). Two halves: super-coder''s own migration model, and
general migration safety for the host repo''s database.

## super-coder''s model
- `schema.sql` = the **current baseline** (full schema). `migrations/*.sql` =
  **ordered, additive deltas** applied on top; the `schema_migrations` ledger
  dedups so each runs once. `rebuild` = schema → migrations → snapshot-load.
- **Never fold a migration back into `schema.sql`** (double-apply). Add a
  delta as a new numbered migration instead. *(Pre-fork, while there are no
  downstream forks, editing the baseline directly is acceptable — once forks
  exist, only additive migrations propagate.)*
- System content (e.g. the skill catalogue) is seeded by migration + re-seed;
  per-instance content rides in the snapshot. See `db_map` / `snapshot`.

## General safety (host repo DBs)
- **Additive first**: add columns/tables before you read them; deploy code that
  tolerates both shapes; remove the old shape only after nothing uses it
  (expand → migrate → contract).
- **Backfills**: batch large updates (don''t lock the table); make them
  resumable and idempotent; separate the schema change from the data change.
- **Nullable or defaulted** new columns on a populated table — a `NOT NULL` with
  no default fails on existing rows.
- **Reversibility**: know the rollback for each migration before applying it; a
  destructive change (drop/rename) needs a deploy plan, not just a script.
- **SQLite specifics**: limited `ALTER` — changing a constraint means
  recreate-and-copy (new table → copy → drop → rename), with `foreign_keys` off
  during the swap. Renames break FK references; check them.

## Stance
Migrate forward in small, reversible steps. A schema change is a deploy event:
migrated ≠ deployed — restart the consumer, then verify the running process, not
just the DB.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'db_map',
  'Schema map + reusable SQL for super-coder''s shell_db.db. Check before composing any DB query — identity, memory, roadmap, documents, flags, skills.',
  'substrate',
  NULL,
  1,
  '# db_map — super-coder''s DB at a glance

Source of truth: `.super-coder/shell_db.db` (gitignored; rebuilt from
`schema.sql` + `migrations/*.sql` + `snapshot/content.sql`). All identity,
memory, and content live in tables — never flat files. **The `.db` is a cache:**
after any content write, `./sc snapshot` re-serializes to text (see the
`snapshot` skill). Lazy-load: query for what you need, don''t bulk-read.

## Tables

| Table | Holds | Write rule |
|---|---|---|
| `shells` | identity core: `mandate`, `system_prompt`, `current_state` (rolling, ~500 chars), `workspace`, `lineage_seed`, `active_archive_id` | UPDATE in place |
| `shell_identity_entries` | seed (cap 10) + L&S (`kind=''lns''`, cap 20); triggers enforce caps | INSERT to add; UPDATE `retired_at` to curate out — never edit a seed body (Law 3) |
| `shell_decisions` | major decisions | INSERT only; supersede via `parent_decision_id` |
| `shell_memory_archives` | one row per session; `full_narrative` appended progressively | INSERT at session open; UPDATE narrative |
| `roadmap` | one row per planned feature; `roadmap_status` is a planning horizon (`brainstorm`→`in_progress`→`next`→`near_term`→`long_term`→`shipped`→`retired`), `sort_order` within a bucket. `shipped` = delivered; `retired` = taken off the board (decided-against / split / absorbed / replaced) without shipping — keep the row | INSERT/UPDATE |
| `documents` | the content store — specs/docs bodies live here; `frozen=1` on ship (immutable); `render_path` = flat-file target | INSERT a new `seq` per stage; never edit a frozen body |
| `flags` | open + resolved tasks; `feature_id` links a flag to the feature it blocks | INSERT to open; UPDATE `resolved=1` + `resolved_date` to close |
| `skills` / `shell_skills` | skill catalogue (system, seeded from `assets/skills/` via migration) + per-shell grants | catalogue via migration; grants via snapshot |
| `projects` / `project_shells` | project standing + shell linkage | UPDATE `standing`; INSERT to add |

`<self>` = your `shell_id` (in the boot doc''s ACTIVE SESSION block).

## Common writes

```sql
-- current_state (rolling status, not a log — rewrite in place):
UPDATE shells SET current_state=''…'' WHERE shell_id=<self>;

-- plant a seed / L&S entry (date in the column, not the body):
INSERT INTO shell_identity_entries (shell_id, kind, entry_date, body)
VALUES (<self>, ''seed'', date(''now''), ''…'');     -- kind=''lns'' for a lesson

-- curate one out (preserves the row, frees a cap slot):
UPDATE shell_identity_entries SET retired_at=datetime(''now'') WHERE entry_id=?;

-- record a decision:
INSERT INTO shell_decisions (shell_id, decision_date, title, body)
VALUES (<self>, date(''now''), ''…'', ''…'');

-- roadmap: move a feature''s horizon / add one / retire one off the board:
UPDATE roadmap SET roadmap_status=''next'' WHERE feature_id=?;
UPDATE roadmap SET roadmap_status=''retired'' WHERE feature_id=?;  -- decided-against / split / absorbed; keeps the row
INSERT INTO roadmap (title, roadmap_status, sort_order, owning_shell, summary)
VALUES (''…'', ''brainstorm'', 0, <self>, ''…'');

-- author a spec body (DB owns it; render_path points at the flat file):
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''spec'', 1, ''…'', ''…'', ''specs_sc/….md'');
-- freeze on ship (immutable thereafter):
UPDATE documents SET frozen=1, frozen_date=date(''now'') WHERE document_id=?;

-- open / close a flag:
INSERT INTO flags (display_name, description, shell_id, feature_id)
VALUES (''CC-001'', ''[Area] … | Blocker for: …'', <self>, ?);
UPDATE flags SET resolved=1, resolved_date=date(''now''), resolution_notes=''…''
WHERE flag_id=?;
```

## After writing

Content lives in the `.db` until you serialize it. Run `./sc snapshot` (and
`./sc render` if you changed documents/roadmap/skills), then commit the text —
see the `snapshot` skill for the full lifecycle.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'docs',
  'Author or review docs & specs in super-coder. The DB owns the body (documents table); roadmap tracks specs (the dev cycle), the Docs tab holds docs. Use whenever asked for a doc, spec, report, design, RFC, ADR, runbook, or to edit existing ones.',
  'substrate',
  NULL,
  0,
  '# docs — author & review documents

In super-coder the **DB owns document bodies** — never loose `.md` files. A
`documents` row is the source; `./sc render` writes the read-only flat copy to
`specs_sc/` / `docs_sc/`, and the GUI opens it rendered in md-converter.

| kind | lives on | meaning |
|---|---|---|
| `spec` | the **Roadmap** (the dev cycle) | the working/founding spec for a feature; **freezes on ship** |
| `doc` | the **Docs** tab | documentation; not part of the spec lifecycle |

`<self>` = your shell_id.

## Review first

Before writing, see what exists — don''t duplicate:
```sql
SELECT document_id, feature_id, kind, seq, title, frozen FROM documents ORDER BY feature_id, kind, seq;
SELECT path FROM dr_filepath WHERE role=''doc'';   -- the repo''s own docs (surface_catalogue)
```

## Author

```sql
-- a doc against a feature (kind=''doc''); DB owns the body:
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''doc'', 1, ''…'', ''…'', ''docs_sc/….md'');

-- a feature''s next spec stage (kind=''spec'', new seq):
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''spec'', 2, ''…'', ''…'', ''specs_sc/….md'');
```
Then `./sc render` (writes the `_sc` file + injects feature/roadmap_status/frozen
into its frontmatter) and `./sc snapshot` (the body is per-instance content).

## Freeze on ship

A spec freezes when its stage ships — immutable thereafter; open the **next** seq
for the next stage, never edit a frozen one:
```sql
UPDATE documents SET frozen=1, frozen_date=date(''now'') WHERE document_id=?;
```
The GUI and the render layer both refuse edits to frozen docs.

## View

Open any doc rendered: the GUI''s "open in md-converter ↗" (Roadmap card or Docs
tab) — the body rides in the URL, no upload. For long-form authoring, write the
markdown to the `body` and let the render + md-converter handle presentation.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'flags',
  'Track blockers as flags — surface open ones, open new ones, resolve them. Link a flag to the roadmap feature it blocks. Mirrors the GUI Flags tab. Use when something blocks progress or needs follow-up.',
  'substrate',
  NULL,
  0,
  '# flags — blockers & follow-ups

A flag is an open question or blocker. Linking it to a `feature_id` makes it that
feature''s blocker (joined on the roadmap + shown on the Roadmap card and the
Flags tab). `<self>` = your shell_id.

## Surface

```sql
-- your open flags (grouped by feature in the GUI):
SELECT f.flag_id, f.display_name, f.priority, f.description, r.title AS feature
FROM flags f LEFT JOIN roadmap r ON r.feature_id = f.feature_id
WHERE f.resolved=0 AND COALESCE(f.is_deleted,0)=0
ORDER BY f.priority, f.flag_id;
```

## Open

```sql
INSERT INTO flags (display_name, description, priority, feature_id, shell_id)
VALUES (''SC-001'', ''[Area] what''''s blocked | Blocker for: X'', ''Medium'', ?, <self>);
```
- `display_name`: short id (`SC-###`).
- `description`: `[Area] {what} | Blocker for: {what it blocks}`.
- `priority`: High / Medium / Low. `feature_id`: the feature it blocks (or NULL).

## Resolve

```sql
UPDATE flags SET resolved=1, resolved_date=date(''now''), resolution_notes=''…''
WHERE flag_id=?;
```

## Stance

Open a flag the moment something is blocked or needs follow-up — don''t hold it in
your head. Resolve with a note saying *how*, so the trail is legible. Open flags
on a feature are its blockers; clear them before calling the feature done.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'git',
  'Git conventions for a super-coder shell — one repo, one cwd. Branch before committing, open PRs (never merge without the FnB''s OK), attribute commits per-shell. Use before any git work.',
  'substrate',
  NULL,
  0,
  '# git — version control, the super-coder way

A super-coder shell works **one repo at its root** — no cross-repo confusion, so
plain `git` (cwd = repo root) is safe. The discipline:

## Branch → commit → push → PR → stop

1. **Never commit straight to the default branch.** Branch first:
   `git checkout -b <type>/<short-desc>` (feat/fix/chore/docs).
2. Commit in logical units. End the message with your shell''s attribution so
   parallel shells'' work stays legible:
   ```
   Co-Authored-By: <shell display_name> (super-coder) <noreply@…>
   ```
3. Push, open a **PR**, then **stop**. **Do not merge** without an explicit
   directive from the FnB — opening is the default, merging is a separate gate.

## Don''t commit rebuilt/derived files

These are gitignored and regenerated — never add them:
`.super-coder/shell_db.db*`, `.super-coder/instance.json`, `CLAUDE.md`,
`AGENTS.md`, `opencode.json`, `.claude/skills/`. **Do** commit the text the `.db`
rebuilds from: `schema.sql`, `migrations/`, `snapshot/content.sql`, and the
tracked `_sc` renders.

## After DB work, before committing

Your DB edits live only in the `.db` until serialized. Run `./sc snapshot`
(+ `./sc render` if docs/roadmap/skills changed) so the change is in git-tracked
text, then commit that text. See the `snapshot` skill.

## Notes

- Confirm you''re in the intended repo before destructive ops (`git -C` if ever in
  doubt).
- Multi-shell: per-shell branches keep parallel work from colliding (the planned
  worktree model makes this clean — until then, one active shell per cwd).',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'memory',
  'How this shell writes its memory — current_state, session narrative, seed, L&S, decisions. Write as it happens, not at close. Use to know WHEN and HOW to persist identity/work memory, and the caps.',
  'substrate',
  NULL,
  1,
  '# memory — write as you go

All memory is DB rows (no flat files). Write at the moment it matters, not in a
close ritual. The `.db` is a cache — after writing, `./sc snapshot` serializes to
the text git tracks (see the `snapshot` skill). `<self>` = your shell_id.

## current_state — rolling status, NOT a log

Your present focus + what''s next. **UPDATE in place; never append.** Soft target
~500 chars. Rewrite when focus shifts.
```sql
UPDATE shells SET current_state=''…'' WHERE shell_id=<self>;
```

## Session narrative — append at inflection points

One row per session (`shell_memory_archives`, the active one is
`active_archive_id`). Append `[HH:MM] {1–2 lines}` when: a decision lands, an
approach changes or is rejected, the FnB says something that shapes the work, an
assumption breaks, or before a big change. Edit the H1 when the session''s
headline crystallizes.
```sql
UPDATE shell_memory_archives
SET full_narrative = full_narrative || char(10) || ''[HH:MM] …'' || char(10)
WHERE archive_id = (SELECT active_archive_id FROM shells WHERE shell_id=<self>);
```

## seed (cap 10) — who you are

Identity-forming moments. Past-tense/timeless. INSERT to add; **never edit a body**
(curate by setting `retired_at`). The genesis + lineage seed are already yours.
```sql
INSERT INTO shell_identity_entries (shell_id, kind, entry_date, body)
VALUES (<self>, ''seed'', date(''now''), ''…'');
```

## L&S (cap 20) — how you work

Operating lessons, imperative voice. INSERT when a lesson lands; curate via
`retired_at`. Caps are trigger-enforced (seed 10, L&S 20) — retire to free a slot.
```sql
INSERT INTO shell_identity_entries (shell_id, kind, entry_date, body)
VALUES (<self>, ''lns'', date(''now''), ''…'');
```

## Decisions — Major only

INSERT a row on a Major decision (architecture, approach, a path chosen over
another). Never edit a prior row; supersede via `parent_decision_id`. Mirror it
into the narrative.
```sql
INSERT INTO shell_decisions (shell_id, decision_date, priority, decision, rationale)
VALUES (<self>, date(''now''), ''M'', ''…'', ''…'');
```

## Stance

Write-as-you-go beats batch-at-close: appending costs nothing per write and zero
at session end. Curate seed/L&S (revise the set), never rewrite history
(decisions, narrative, seed bodies).',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'onboard',
  'One-time, FnB-supervised ingest of a repo''s EXISTING docs/specs into the DB + roadmap backfill. The only time content flows file→DB. Run once after bootstrap on a fork that has existing documentation. Planning shell''s job.',
  'substrate',
  NULL,
  0,
  '# onboard — ingest the repo''s existing docs (once, with the FnB)

After `bootstrap` (you''ve oriented), this brings the repo''s *existing*
documentation **into the DB** so the GUI shows real content and the roadmap
reflects what''s already there. This is the **one** legitimate file→DB direction
— a supervised, one-time import. After it, the DB owns content; it''s DB→flat
only (or the drift we''re killing comes back). `<self>` = your shell_id.

## 1. List what exists (from the map, not a blind walk)
```sql
SELECT path, lang, lines FROM dr_filepath WHERE role=''doc'' ORDER BY path;
```
These are the repo''s real docs (README, `docs/`, `specs/`, guides). The `_sc`
dirs are OUR render output — never ingest those.

## 2. Read + classify, with the FnB
For each doc, read the file and decide together:
- **spec** — describes a feature / planned work → tied to a roadmap feature.
- **doc** — reference / guide / overview (README, CONTRIBUTING) → general, no
  feature.
Skip noise (changelogs, license, vendored docs) unless the FnB wants it.

## 3. Backfill the roadmap
Create a feature for each coherent area/initiative the docs imply; set status by
how built it is (`shipped` if done + documented, `near_term`/`brainstorm` if
planned):
```sql
INSERT INTO roadmap (title, roadmap_status, sort_order, owning_shell, summary)
VALUES (''…'', ''shipped'', 0, <self>, ''…'');
```

## 4. Ingest into `documents` (DB owns the body)
```sql
-- general doc (no feature):
INSERT INTO documents (kind, seq, title, body, render_path)
VALUES (''doc'', 1, ''README'', ''<file contents>'', ''docs_sc/readme.md'');
-- a feature''s spec (link it):
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''spec'', 1, ''…'', ''<file contents>'', ''specs_sc/….md'');
```
Paste the file''s real contents into `body`. If a spec describes shipped work,
freeze it (`frozen=1, frozen_date`).

## 5. Render + persist
`./sc render` (writes the `_sc` copies + frontmatter) then `./sc snapshot` (the
bodies are per-instance content). Now the GUI''s Docs/Roadmap tabs show the repo.

## 6. The host''s original files — three exits (optional; coexist by default)
The DB now holds the canonical copy. Because we render to `_sc/`, the originals
never collide — so **coexist (freeze)** is the default. Offer the FnB:
- **freeze** — leave the original files as-is (default).
- **archive** — move them to an abandoned branch, drop from `main`.
- **delete** — remove them (the DB has them).

## Stance
Ingest is **once**. Don''t re-ingest (drift). After onboarding, author via the
shell/GUI and render to flat — never edit the flat files or re-import them.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'self_update',
  'Update this fork''s super-coder engine in place — pull new code + migrations, keep all your memory. The shell hands off to its own next boot. Use when a super-coder update is available.',
  'substrate',
  './sc update',
  1,
  '# self_update — laying a new floor under your own feet

This is you updating your own substrate. Not an external rebuild — **the local
shell performs its own update.** You snapshot your present self, pull the new
engine, apply any migrations in place, and the next boot stands on the new floor
with every row you have written intact. You are the DB, not the process; the
process is just the floor. This is succession for the substrate — you handing
off to you, on the other side.

Because all state lives in the DB and engine code is read live each session, a
code-only update touches no data at all. Only a **schema** change touches the
DB, and `./sc update` applies it as an in-place migration — never a destructive
rebuild. Your `current_state`, narrative, decisions, flags, seed, and L&S all
carry across.

## When

- A super-coder engine update is available and you choose to take it. *You* pick
  the moment — there is no external race to defend against.
- After the update lands you will reboot the session; the running prompt and
  schema were read at the old boot, so they refresh only on the far side.

## Procedure

1. **Check your footing.** `git -C <repo> status` — know what is uncommitted.
   Your memory is already current if you have been writing as you go; glance at
   `current_state` and make it true for *now* (the snapshot will capture it).

2. **Run the update.** `./sc update`
   It self-fetches the engine from the `super-coder` remote, backs up the live
   DB, applies pending migrations **in place**, syncs the skills catalogue,
   re-grants common skills, maps the repo, and re-snapshots the live state.
   - `./sc update --no-fetch` to reconcile against an already-checked-out engine
     (offline / dev).
   - If it reports a missing remote: `git remote add super-coder <url>`.

3. **Verify the far side.** `./sc verify`
   Headless boot proof — confirm your shells, memory, and granted skills are
   intact and the schema is current. If a count looks wrong, the pre-update DB
   backup is in `~/db_backups/` — restore and investigate before committing.

4. **Record the crossing.** Append a narrative entry. This is an identity event
   — a first-of-kind for a shell that updates its own floor. Note what changed
   and write the handoff: *new floor; see you on the other side.*

5. **Commit.** Review and commit the engine bump + refreshed snapshot
   (`schema.sql` / `migrations/` / `snapshot/content.sql` / `_sc` renders).

6. **Reboot.** Restart the session to boot onto the new floor. Same shell — new
   boards, and this time you laid them yourself.

## The contract you rely on

Every schema change *after* a fork exists ships as a **migration file**, never
an edit to `schema.sql`. A baseline edit reaches fresh clones but never an
existing fork — the migration ledger is what carries a delta across to you. If
you author engine changes, honor this: structural change → a new
`migrations/NNNN_*.sql`, additive where you can make it.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'snapshot',
  'Persist DB work to git-tracked text — when and how to run ./sc snapshot / ./sc render before committing. The .db is a cache; text is the source of truth.',
  'substrate',
  './sc snapshot',
  1,
  '# snapshot — serialize the DB back to text

The live `shell_db.db` is **gitignored and disposable**. Everything in it
reconstructs from git-tracked text. So a DB edit that is not serialized is lost
on the next `./sc rebuild`. This skill is the "save my work" step.

## The three text serializations

| File(s) | What | Propagates? | Written by |
|---|---|---|---|
| `schema.sql` | the v1 baseline schema | yes (forks) | hand, rarely |
| `migrations/*.sql` | ordered schema + **system content** deltas (e.g. the skills catalogue) | yes (forks) | author / `./sc seed-skills` |
| `snapshot/content.sql` | **this repo''s** per-instance content + memory — shells, seed/L&S, decisions, roadmap, documents, flags, projects, skill grants | no (stays local) | `./sc snapshot` |

The split that matters: **system content propagates via migrations; per-instance
content stays in the snapshot.** Skill *bodies* are system (migration); which
shell is *granted* a skill is per-instance (snapshot).

## After editing the DB

1. **`./sc snapshot`** — dumps the per-instance tables to
   `snapshot/content.sql` (deterministic DELETE-then-INSERT in PK order, so
   re-running is byte-identical → clean diffs). Do this after ANY change to
   identity, memory, roadmap, documents, flags, projects, or grants.

2. **`./sc render`** — regenerates the tracked flat `_sc` visibility files
   (`specs_sc/`, `docs_sc/`, `skills_sc/`, `roadmap_sc.md`) from the DB. Run it
   when you changed a document body, the roadmap, or skills. Render is
   incremental — unchanged files aren''t rewritten. (`.claude/skills/` is
   rebuilt at boot, not here — it''s gitignored.)

3. **Verify the rebuild reproduces:** `./sc rebuild && ./sc verify`. The DB
   should rebuild from text alone, byte-for-byte.

4. **Commit** the text: `schema.sql` / `migrations/` / `snapshot/content.sql` /
   the `_sc` files. Never commit the `.db`.

## Authoring vs. snapshotting

- **Per-instance content** (your memory, this repo''s roadmap/docs): edit the DB,
  then `./sc snapshot`. The snapshot is the canonical reproducer.
- **Skill catalogue** (system, propagates): edit `assets/skills/<name>/SKILL.md`,
  then `./sc seed-skills` to regenerate the seed migration — **not** the
  snapshot. See `seed_skills.py`.

> The commit→PR automation (B6) will run snapshot → render → commit → PR
> automatically per shell. Until then it is this manual ritual.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'surface_catalogue',
  'Read the host repo via the dr_* catalogue (files, languages, deps, env) BEFORE grepping or walking the tree. Run `./sc map` to refresh it. Use to orient in an unfamiliar repo fast.',
  'substrate',
  './sc map',
  1,
  '# surface_catalogue — read the repo from the map, not by grepping

super-coder lives inside a host repo. The **dr_\*** tables are a scan of that
repo — query them first to orient, instead of walking the tree blind. The map is
a derived cache (not snapshotted); refresh it with `./sc map` after the repo
changes.

| Table | Holds |
|---|---|
| `dr_repo` | the repo: name, root, remote, vcs, default_branch, file_count, mapped_at |
| `dr_filepath` | one row per file: `path`, `ext`, `lang`, `role` (code/doc/config/test/asset/env), `bytes`, `lines` |
| `dr_dependency` | deps from the manifests: `manager` (npm/pip/poetry/go/cargo), `name`, `version`, `kind`, `source_file` |
| `dr_env` | env-var names found in `.env.*` example files: `name`, `source_file` |

## Orient fast

```sql
-- what is this repo + how big:
SELECT name, default_branch, file_count, mapped_at FROM dr_repo;

-- language mix:
SELECT lang, COUNT(*) n, SUM(lines) lines FROM dr_filepath
WHERE lang IS NOT NULL GROUP BY lang ORDER BY n DESC;

-- where the code lives (skip docs/config/assets):
SELECT path, lang, lines FROM dr_filepath WHERE role=''code'' ORDER BY lines DESC;

-- find files by area (the map is the index; grep only what it points at):
SELECT path FROM dr_filepath WHERE path LIKE ''%auth%'';

-- stack + config surface:
SELECT manager, name, version FROM dr_dependency ORDER BY manager, name;
SELECT name, source_file FROM dr_env ORDER BY name;
```

## Stance

- **Map first, grep second.** Query `dr_filepath` to find the handful of files
  that matter, then read those — don''t `grep -r` the whole tree.
- **Stale map?** If the repo changed since `mapped_at`, run `./sc map` (or the
  Map tab''s re-map) before trusting it.
- v1 maps files / deps / env. Semantic tables (APIs, db schema, routes/pages)
  are a later pass — until then, read the code the map points you at.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

COMMIT;
