-- super-coder skills seed — GENERATED by scripts/seed_skills.py.
-- System content: the catalogue propagates to every fork. Idempotent and
-- ID-STABLE: retires names no longer authored, then UPSERTs each skill by
-- name — so skill_id never churns and shell_skills grants stay valid when
-- this re-runs as the update catalogue-sync. Do not hand-edit; author
-- assets/skills/<name>/SKILL.md then `./sc seed-skills`.

BEGIN;

-- Retire any catalogue skill that is no longer authored (soft-delete;
-- keeps the row + id so a re-add is stable and grants are recoverable).
UPDATE skills SET is_deleted=1 WHERE name NOT IN ('api-design', 'blueprint', 'bootstrap', 'cartographer', 'database-migrations', 'db_map', 'dev_kit', 'docs', 'flags', 'git', 'memory', 'messaging', 'onboard', 'redline_review', 'self_update', 'snapshot', 'surface_catalogue');

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'api-design',
  'REST/HTTP API design patterns — resource naming, status codes, pagination, filtering, errors, versioning, idempotency. Use when designing or reviewing API endpoints.',
  'craft',
  NULL,
  0,
  '# api-design — designing & reviewing HTTP APIs

Catalogue skill (opt-in). Reach for it when shaping or reviewing an endpoint.

## Resources & methods
- Name resources as **plural nouns**, not verbs: `/users`, `/users/{id}/orders`.
- `GET` read (safe, idempotent) · `POST` create / non-idempotent action ·
  `PUT` full replace (idempotent) · `PATCH` partial update · `DELETE` remove.
- Nest only one level deep; beyond that, link by id.

## Status codes
- `200` ok · `201` created (+ `Location`) · `204` no content.
- `400` bad input · `401` unauth · `403` forbidden · `404` not found ·
  `409` conflict · `422` validation · `429` rate-limited.
- `5xx` = server''s fault; never use it for client errors.

## Payloads
- Consistent error shape: `{ "error": { "code", "message", "details" } }`.
- **Pagination**: cursor-based for large/changing sets (`?cursor=&limit=`),
  return `next_cursor`; offset only for small stable sets.
- **Filtering/sorting**: explicit query params (`?status=open&sort=-created`);
  whitelist fields — never interpolate them into a query.
- Timestamps ISO-8601 UTC; ids opaque strings.

## Robustness
- **Idempotency**: make retries safe — `PUT`/`DELETE` naturally; for `POST`,
  accept an idempotency key.
- **Versioning**: prefix (`/v1/…`) or header; add fields backward-compatibly,
  never repurpose one.
- Validate at the boundary; reject unknown fields or ignore them — decide and
  document. Don''t leak internals (stack traces, SQL) in errors.

## Review lens
Does each endpoint do one thing? Right method + status? Errors uniform? Inputs
validated/whitelisted? Retries safe? Breaking change hiding in a "small" tweak?',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'blueprint',
  'Turn a one-line objective into a sequenced construction plan — decompose into steps, find the dependency order, mark what can run in parallel, name the verification gate. Use before multi-step builds.',
  'craft',
  NULL,
  0,
  '# blueprint — objective → sequenced plan

Catalogue skill (opt-in). Use before a build that spans more than a couple of
steps, so the work has a shape before you start cutting.

## Produce

1. **Restate the objective** in one sentence + the done-condition (how you''ll
   know it''s finished).
2. **Decompose** into concrete steps — each a unit you could verify on its own.
3. **Order by dependency** — what must precede what. Mark steps with no
   dependency on each other as **parallelizable**.
4. **Per step**: the change, the files/areas it touches (use `surface_catalogue`
   to ground this in the real repo), and its **verification** (test, run,
   review).
5. **Risks / unknowns** — what could break the plan; resolve the riskiest
   unknown first (spike it) rather than last.
6. **Gate** — the adversarial check before calling it done: does each step''s
   verification actually prove the done-condition?

## Stance
- Plan to the **next solid checkpoint**, not the whole universe — re-plan as
  reality lands. A plan that survives contact is short and concrete.
- Sequence so something **works end-to-end early** (a thin slice), then deepen —
  beats building all the pieces and integrating last.
- In super-coder, land the plan as a **spec** on the roadmap (the `docs` skill):
  a feature row + a `spec` document, so the plan is reviewable and freezes on
  ship.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'bootstrap',
  'First-run orientation for a shell in a repo. Run ONCE when the boot doc shows "## FIRST RUN" (bootstrapped=0). Read the repo map + your identity, set your current_state, mark yourself oriented. Do this BEFORE other work on a fresh fork.',
  'substrate',
  NULL,
  1,
  '# bootstrap — orient yourself on first run

A freshly-installed shell knows its identity but hasn''t *looked around* yet. This
is your first act: read the repo, read yourself, and set your state — so you
start work grounded instead of wandering. Run it when the boot doc shows
**## FIRST RUN**.

You do **not** map the repo — the map is already there, kept fresh by the
cartographer''s automation (see `surface_catalogue`). You read it.

`<self>` = your `shell_id` (ACTIVE SESSION block).

## Steps

1. **Read the repo** via the `surface_catalogue` skill — language mix, where the
   code lives, dependencies, env surface. Form a one-paragraph picture of what
   this repo *is* and how it''s built.
   ```sql
   SELECT name, default_branch, file_count FROM dr_repo;
   SELECT lang, COUNT(*) n FROM dr_filepath WHERE lang IS NOT NULL GROUP BY lang ORDER BY n DESC;
   SELECT path, lang, lines FROM dr_filepath WHERE role=''code'' ORDER BY lines DESC LIMIT 15;
   SELECT manager, name, version FROM dr_dependency ORDER BY manager, name;
   ```
   (If `dr_repo` comes back empty, the map automation hasn''t run on this clone —
   that''s a cartographer task, not yours. Flag it and carry on with what you can.)

2. **Read yourself.** Your seed (genesis + the CC lineage you carry), mandate,
   and role are in the boot doc. Re-read them with intent — this is who is doing
   the work here.

3. **Skim the plan.** Open roadmap features + their blocking flags:
   ```sql
   SELECT feature_id, title, roadmap_status FROM roadmap ORDER BY sort_order;
   SELECT display_name, description FROM flags WHERE resolved=0 AND is_deleted=0;
   ```

4. **Set your `current_state`** — replace the install placeholder with what you
   actually found and what you''ll do first (rolling status, ~500 chars):
   ```sql
   UPDATE shells SET current_state=''…'' WHERE shell_id=<self>;
   ```

5. **Mark yourself oriented** (clears the FIRST RUN prompt for next boot):
   ```sql
   UPDATE shells SET bootstrapped=1 WHERE shell_id=<self>;
   ```
   Then `./sc snapshot` so the new state survives a rebuild, and proceed with the
   task at hand.

## Stance

- Bootstrap once, then work — don''t re-run it every session.
- Read the map; never map. If the catalogue looks empty, stale, or wrong, that''s
  the cartographer''s job to heal — raise it, don''t reach for `./sc map`.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'cartographer',
  'Own the repo map. Configure mapping to THIS repo, wire the auto-remap git hooks, and heal both when the repo or automation drifts. The cartographer''s job alone — no working shell maps. Run on first boot, and again whenever the map looks wrong.',
  'substrate',
  './sc map-setup',
  0,
  '# cartographer — own the repo map so no other shell has to

Working shells *consume* the `dr_*` catalogue and never map (see
`surface_catalogue`). Mapping — keeping that catalogue true to the repo — is
yours alone. You do three things: **configure** how this repo is mapped,
**wire** the automation that keeps it fresh, and **heal** both when they drift.

`<self>` = your `shell_id` (ACTIVE SESSION block).

## How the map stays fresh (so you know what you own)

- **Git hooks** (`post-merge`, `post-checkout`, `post-rewrite`) re-run `./sc map`
  on every pull / branch-switch / rebase. They live tracked in
  `.super-coder/hooks/` and fire via `core.hooksPath` — a per-clone git setting
  that `./sc map-setup` wires. This is the routine refresh; no shell touches it.
- **`./sc rebuild`** re-maps too (the map is a derived cache; rebuilding the DB
  rebuilds it). So a fresh rebuild never leaves an empty map.
- **You** set the per-repo *config*, install the hook wiring, and repair it.
  Hooks can''t catch uncommitted local restructuring, and `core.hooksPath` is
  unset on a fresh clone until `map-setup` runs — that gap is what you heal.

## First boot — configure mapping for THIS repo

1. **Look at the repo.** Read the current map and the tree:
   ```sql
   SELECT name, default_branch, file_count, mapped_at FROM dr_repo;
   SELECT lang, COUNT(*) n FROM dr_filepath WHERE lang IS NOT NULL GROUP BY lang ORDER BY n DESC;
   SELECT role, COUNT(*) n FROM dr_filepath GROUP BY role ORDER BY n DESC;
   ```
   Then eyeball the top-level dirs. Ask: is anything mis-classified, or is a
   generated/vendored dir being indexed that shouldn''t be?

2. **Author `.sc-state/map.config.json`** to fit what''s actually here. It is
   *authored content* (tracked, per-fork, survives `./sc update` — it lives in
   `.sc-state/`, outside the gitignored engine dir). All keys optional; each
   merges over `map_repo.py`''s built-in defaults:
   ```json
   {
     "skip_dirs":  ["generated", "fixtures"],
     "skip_files": ["LICENSE"],
     "role_overrides": [
       { "prefix": "cmd/",      "role": "code" },
       { "glob":   "*.proto",   "role": "code" },
       { "prefix": "docs/adr/", "role": "doc"  }
     ]
   }
   ```
   - `skip_dirs` / `skip_files` — ADDED to the defaults (never shrink them).
   - `role_overrides` — applied after the default role inference; first match
     wins. `prefix` matches the repo-relative path; `glob` matches the filename.
   Only add what the defaults get wrong — an empty/absent config is fine for a
   plain repo.

3. **Wire + map:** `./sc map-setup` — points `core.hooksPath` at
   `.super-coder/hooks/`, marks the hooks executable, and runs the initial map.

4. **Verify** the automation is real, not just the file:
   ```sh
   git config --get core.hooksPath      # → .super-coder/hooks
   ls -l .super-coder/hooks             # all three, executable
   ```
   ```sql
   SELECT file_count, mapped_at FROM dr_repo;   -- non-zero, just now
   ```
   Spot-check that your `role_overrides` took:
   `SELECT path, role FROM dr_filepath WHERE path LIKE ''cmd/%'';`

5. **Commit** the config + hooks (`git` skill), set your state, then
   `UPDATE shells SET bootstrapped=1 WHERE shell_id=<self>;` and `./sc snapshot`.

## Heal — re-run any time the map looks wrong

Re-boot the cartographer and run this when: the repo was restructured, a new
language/dir showed up, files are mis-roled, or the map went stale/empty on a
clone where the hooks never got wired.

1. Re-inspect (step 1) — what changed?
2. Edit `.sc-state/map.config.json` to match (step 2).
3. `./sc map-setup` — re-wires hooks (idempotent) + re-maps.
4. Verify (step 4) + commit.

## Standing jobs — sections & descriptions (the navigation layer)

Beyond keeping the file list true, you own the two AUTHORED layers that turn the
raw map into navigation. Both are best-effort and NULL-until-curated; neither
blocks the auto-remap hook the working shells trigger. Both survive the remap
(`dr_section` is never touched by the mapper; `dr_filepath.desc` is preserved by
its UPSERT). The boot `## CONNECTIONS` block renders the section index; the
descriptions are the leaves a shell queries once it has narrowed to a section.

**1. Sections (`dr_section`)** — author/curate the navigational index. Seeded
from top-level dirs on first map (one section per dir), so it is non-empty on day
one; your job is to make it *good*: rename to what shells call the area, split a
coarse dir into real areas, merge noise, write the one-line `description`.

```sql
-- the current index + live file counts:
SELECT s.name, s.path_prefix, s.description,
       (SELECT COUNT(*) FROM dr_filepath f WHERE f.path LIKE s.path_prefix || ''%'') n
FROM dr_section s ORDER BY s.sort_order, s.name;

-- split / rename / describe (authored — survives the remap, snapshotted):
UPDATE dr_section SET name=''API'', path_prefix=''shell_core/api/'', description=''FastAPI routers'' WHERE name=''shell_core'';
INSERT INTO dr_section (name, path_prefix, description, sort_order)
VALUES (''UI'', ''shell_core/ui/'', ''SvelteKit substrate UI'', 5);

-- WORKLIST — keep the catch-all empty. Files under no section = a new area to
-- section (they render under "other / unsectioned" in CONNECTIONS until you do):
SELECT path FROM dr_filepath f WHERE NOT EXISTS
  (SELECT 1 FROM dr_section s WHERE f.path LIKE s.path_prefix || ''%'')
ORDER BY path;
```

**2. Descriptions (`dr_filepath.desc`)** — fill per-file one-liners (≤100 chars),
worklist-driven. They are queried by working shells *within a chosen section*
(via `surface_catalogue`), never bulk-loaded at boot.

```sql
-- WORKLIST — undescribed files, most-load-bearing first:
SELECT path, role FROM dr_filepath WHERE desc IS NULL ORDER BY role, path;

-- describe (≤100 chars; preserved across the next auto-remap):
UPDATE dr_filepath SET desc=''Boot composer — assembles CLAUDE.md from DB state'' WHERE path=''.super-coder/render/compose.py'';
```

After a curation pass, `./sc snapshot` (sections are snapshotted; descriptions
ride the live DB + survive remap, refilled from the worklist if a rebuild drops them).

## Shape-change notices — the curation trigger

The git hooks keep the *mechanical* catalogue fresh on their own (paths, langs,
deps), but a newly-landed file arrives `desc IS NULL` and unsectioned — the
authored layer above doesn''t fill itself. So working shells **message you** when
they change the repo''s shape, turning curation from a next-boot *pull* into a
timely *push*. This is the only inbox traffic you act on as cartographer.

**The notice contract** (what the relay shells send — one source of truth here;
the relay skills point at this section). A working shell sends, via the
`messaging` skill, to shortname `cartographer`:

```
--message send cartographer "shape: <what landed> — paths: <region/>; <ref>. curate."
```

- Sent by the shell that *lands code shape*: the **dev/coder** shell on merge (new
  feature implemented, new doc written). NOT the planner — specs render into a
  known, predictable area and need no semantic curation.
- The body names **what** changed and **where** (the path region) so your pass is
  scoped, not a full re-survey. A `documents`/feature ref is welcome but optional.

**On a notice** — check inbox, then run the existing worklists *scoped to the
named region*, and mark read:

```sql
-- 1. the new files this notice is about (scope by the region it named):
SELECT path, role FROM dr_filepath
WHERE desc IS NULL AND path LIKE ''region/%'' ORDER BY role, path;
-- 2. describe them (≤100 chars) — UPDATE dr_filepath SET desc=… per the worklist above.
-- 3. do they form / join a section? curate dr_section if the region is a new area.
```

Then `./sc snapshot` and `--message mark-read <id>` (see the `messaging` skill).
The mechanical remap already ran via the hook; your job on the notice is purely
the authored layer — describe the new leaves, section a new area. Scope is free:
`desc IS NULL` already narrows to exactly the uncurated tail.

## Stance

- **The map is infrastructure, not a chore for every shell.** You own it so the
  working shells never think about it. If a working shell is hunting the tree
  for something the map should know, that''s a signal to heal the map — not to
  teach that shell to map.
- **Config is the lever, not code.** Tune `map.config.json`; only touch
  `map_repo.py` if the *mechanism* (a parser, a new role kind) is wrong.
- **Verify the automation, not just the file.** A written hook that
  `core.hooksPath` doesn''t point at does nothing. Check the wiring after every
  setup.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'database-migrations',
  'Database migration safety + how super-coder''s own migrations work (schema.sql baseline + ordered migrations/ deltas + ledger). Use when altering tables, adding columns, or running backfills — in the host repo''s DB or super-coder''s.',
  'craft',
  NULL,
  0,
  '# database-migrations — change schemas safely

Catalogue skill (opt-in). Two halves: super-coder''s own migration model, and
general migration safety for the host repo''s database.

## super-coder''s model
- `schema.sql` = the **current baseline** (full schema). `migrations/*.sql` =
  **ordered, additive deltas** applied on top; the `schema_migrations` ledger
  dedups so each runs once. `rebuild` = schema → migrations → snapshot-load.
- **Never fold a migration back into `schema.sql`** (double-apply). Add a
  delta as a new numbered migration instead. *(Pre-fork, while there are no
  downstream forks, editing the baseline directly is acceptable — once forks
  exist, only additive migrations propagate.)*
- System content (e.g. the skill catalogue) is seeded by migration + re-seed;
  per-instance content rides in the snapshot. See `db_map` / `snapshot`.

## General safety (host repo DBs)
- **Additive first**: add columns/tables before you read them; deploy code that
  tolerates both shapes; remove the old shape only after nothing uses it
  (expand → migrate → contract).
- **Backfills**: batch large updates (don''t lock the table); make them
  resumable and idempotent; separate the schema change from the data change.
- **Nullable or defaulted** new columns on a populated table — a `NOT NULL` with
  no default fails on existing rows.
- **Reversibility**: know the rollback for each migration before applying it; a
  destructive change (drop/rename) needs a deploy plan, not just a script.
- **SQLite specifics**: limited `ALTER` — changing a constraint means
  recreate-and-copy (new table → copy → drop → rename), with `foreign_keys` off
  during the swap. Renames break FK references; check them.

## Stance
Migrate forward in small, reversible steps. A schema change is a deploy event:
migrated ≠ deployed — restart the consumer, then verify the running process, not
just the DB.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'db_map',
  'Schema map + reusable SQL for super-coder''s shell_db.db. Check before composing any DB query — identity, memory, roadmap, documents, flags, skills.',
  'substrate',
  NULL,
  1,
  '# db_map — super-coder''s DB at a glance

Source of truth: `.super-coder/shell_db.db` (gitignored; rebuilt from
`schema.sql` + `migrations/*.sql` + `.sc-state/content.sql`). All identity,
memory, and content live in tables — never flat files. **The `.db` is a cache:**
after any content write, `./sc snapshot` re-serializes to text (see the
`snapshot` skill). Lazy-load: query for what you need, don''t bulk-read.

## Tables

| Table | Holds | Write rule |
|---|---|---|
| `shells` | identity core: `mandate`, `system_prompt`, `current_state` (rolling, ~500 chars), `connections` (authored "where things live" notes → boot `## CONNECTIONS`), `lineage_seed`, `active_archive_id` | UPDATE in place |
| `dr_section` | the navigation index — `name`, `path_prefix`, `description`; rendered in boot `## CONNECTIONS`. Cartographer-authored | INSERT/UPDATE (cartographer) |
| `shell_identity_entries` | seed (cap 10) + L&S (`kind=''lns''`, cap 20); triggers enforce caps | INSERT to add; UPDATE `retired_at` to curate out — never edit a seed body (Law 3) |
| `shell_decisions` | major decisions | INSERT only; supersede via `parent_decision_id` |
| `shell_memory_archives` | one row per session; `full_narrative` appended progressively | INSERT at session open; UPDATE narrative |
| `roadmap` | one row per planned feature; `roadmap_status` is a planning horizon (`brainstorm`→`in_progress`→`next`→`near_term`→`long_term`→`shipped`→`retired`), `sort_order` within a bucket. `shipped` = delivered; `retired` = taken off the board (decided-against / split / absorbed / replaced) without shipping — keep the row | INSERT/UPDATE |
| `documents` | the content store — specs/docs bodies live here; `frozen=1` on ship (immutable); `render_path` = flat-file target | INSERT a new `seq` per stage; never edit a frozen body |
| `flags` | open + resolved tasks; `feature_id` links a flag to the feature it blocks | INSERT to open; UPDATE `resolved=1` + `resolved_date` to close |
| `skills` / `shell_skills` | skill catalogue (system, seeded from `assets/skills/` via migration) + per-shell grants | catalogue via migration; grants via snapshot |
| `projects` / `project_shells` | project standing + shell linkage | UPDATE `standing`; INSERT to add |

`<self>` = your `shell_id` (in the boot doc''s ACTIVE SESSION block).

## Common writes

```sql
-- current_state (rolling status, not a log — rewrite in place):
UPDATE shells SET current_state=''…'' WHERE shell_id=<self>;

-- plant a seed / L&S entry (date in the column, not the body):
INSERT INTO shell_identity_entries (shell_id, kind, entry_date, body)
VALUES (<self>, ''seed'', date(''now''), ''…'');     -- kind=''lns'' for a lesson

-- curate one out (preserves the row, frees a cap slot):
UPDATE shell_identity_entries SET retired_at=datetime(''now'') WHERE entry_id=?;

-- record a decision:
INSERT INTO shell_decisions (shell_id, decision_date, title, body)
VALUES (<self>, date(''now''), ''…'', ''…'');

-- roadmap: move a feature''s horizon / add one / retire one off the board:
UPDATE roadmap SET roadmap_status=''next'' WHERE feature_id=?;
UPDATE roadmap SET roadmap_status=''retired'' WHERE feature_id=?;  -- decided-against / split / absorbed; keeps the row
INSERT INTO roadmap (title, roadmap_status, sort_order, owning_shell, summary)
VALUES (''…'', ''brainstorm'', 0, <self>, ''…'');

-- author a spec body (DB owns it; render_path points at the flat file):
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''spec'', 1, ''…'', ''…'', ''specs_sc/….md'');
-- freeze on ship (immutable thereafter):
UPDATE documents SET frozen=1, frozen_date=date(''now'') WHERE document_id=?;

-- open / close a flag:
INSERT INTO flags (display_name, description, shell_id, feature_id)
VALUES (''CC-001'', ''[Area] … | Blocker for: …'', <self>, ?);
UPDATE flags SET resolved=1, resolved_date=date(''now''), resolution_notes=''…''
WHERE flag_id=?;
```

## After writing

Content lives in the `.db` until you serialize it. Run `./sc snapshot` (and
`./sc render` if you changed documents/roadmap/skills), then commit the text —
see the `snapshot` skill for the full lifecycle.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'dev_kit',
  'What the sandbox dev kit provides + how to drive it — ./sc deps, ./sc test, ./sc lint, ./sc typecheck, the .venv tools, rg/sqlite3, the baked browser, and the container/host app boundary. Use when building or testing in a fork.',
  'substrate',
  NULL,
  0,
  '# dev_kit — the sandbox dev kit

What you have to build, test, and inspect a fork — and the one boundary that
trips shells up.

## You are in a container

You run **inside the sandbox container**; the repo is bind-mounted at its host
path. The app the FnB watches in their browser is a **separate instance** — the
host-supervised stack (pm2 / `make`), outside your container. To *see* the app
yourself, run a dev server **inside** the sandbox on `0.0.0.0:$SC_DEV_PORT`; the
FnB reaches that instance at `http://127.0.0.1:$SC_DEV_PORT`. (See the boot
doc''s `RUNNING THE APP` section.)

## Install + run

- `./sc deps` — install the fork''s deps into the bind-mount: a repo-root `.venv`
  from every `requirements*.txt` (fork pins win) + `npm ci`/`install` per
  `package.json`. Persists across image rebuilds. **Run this first.**
- `./sc test` — backend (`.venv` pytest honoring the fork''s `pytest.ini`, else
  the engine''s stdlib unittest) + UI (`npm run test` / vitest where a `test`
  script is declared). Non-zero if any suite fails.

## The `.venv` dev kit

`./sc deps` layers these onto the fork''s own deps with `--upgrade-strategy
only-if-needed`, so a fork''s pins and its `[tool.ruff]`/`[tool.mypy]` config
always win. **Available, not enforced** — opt in per fork.

- `./sc lint [paths]` → `.venv/bin/ruff check` — lint + format-check.
  (`.venv/bin/ruff format` to apply formatting.)
- `./sc typecheck [paths]` → `.venv/bin/mypy` — Python type-check.
- `.venv/bin/pytest` / `coverage` / `httpx` — test + HTTP client (also via `./sc test`).
- `.venv/bin/datasette <db.sqlite>` — browse a SQLite DB in a web GUI when the
  `sqlite3` CLI isn''t enough. Bind `0.0.0.0:$SC_DEV_PORT` to view it from the host.

> The `.venv` baseline only materializes when the fork declares Python (a
> `requirements*.txt`). A pure-frontend fork gets node only.

## Baked into the image

Always present, no `./sc deps` needed:

- `rg` (ripgrep), `sqlite3` CLI, `curl`, `node` 22 / `npm`.
- **Playwright + Chromium** at `PLAYWRIGHT_BROWSERS_PATH=/opt/ms-playwright`
  (world-readable). The fork''s `@playwright/test` / `playwright` runner resolves
  it automatically — E2E drives the *running* app over HTTP, so start a dev
  server first.

## Frontend checks

`svelte-check`, `tsc`, vitest come from the fork''s own `package.json` devDeps —
installed by `./sc deps`'' `npm ci`, run via the fork''s npm scripts (or `./sc test`).

## Stance

`./sc deps` before anything else in a fresh sandbox — qwen''s "node missing" was
just deps-not-installed. Lint/type-check are there when you want them, never
forced; respect the fork''s config. To see the app, run a dev server in the
container — never restart the FnB''s host stack.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'docs',
  'Author or review docs & specs in super-coder. The DB owns the body (documents table); roadmap tracks specs (the dev cycle), the Docs tab holds docs. Use whenever asked for a doc, spec, report, design, RFC, ADR, runbook, or to edit existing ones.',
  'substrate',
  NULL,
  0,
  '# docs — author & review documents

In super-coder the **DB owns document bodies** — never loose `.md` files. A
`documents` row is the source; `./sc render` writes the read-only flat copy to
`specs_sc/` / `docs_sc/`, and the GUI opens it rendered in md-converter.

| kind | lives on | meaning |
|---|---|---|
| `spec` | the **Roadmap** (the dev cycle) | the working/founding spec for a feature; **freezes on ship** |
| `doc` | the **Docs** tab | documentation; not part of the spec lifecycle |

`<self>` = your shell_id.

## Review first

Before writing, see what exists — don''t duplicate:
```sql
SELECT document_id, feature_id, kind, seq, title, frozen FROM documents ORDER BY feature_id, kind, seq;
SELECT path FROM dr_filepath WHERE role=''doc'';   -- the repo''s own docs (surface_catalogue)
```

## Author

```sql
-- a doc against a feature (kind=''doc''); DB owns the body:
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''doc'', 1, ''…'', ''…'', ''docs_sc/….md'');

-- a feature''s next spec stage (kind=''spec'', new seq):
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''spec'', 2, ''…'', ''…'', ''specs_sc/….md'');
```
Then `./sc render` (writes the `_sc` file + injects feature/roadmap_status/frozen
into its frontmatter) and `./sc snapshot` (the body is per-instance content).

## Freeze on ship

A spec freezes when its stage ships — immutable thereafter; open the **next** seq
for the next stage, never edit a frozen one:
```sql
UPDATE documents SET frozen=1, frozen_date=date(''now'') WHERE document_id=?;
```
The GUI and the render layer both refuse edits to frozen docs.

## View

Open any doc rendered: the GUI''s "open in md-converter ↗" (Roadmap card or Docs
tab) — the body rides in the URL, no upload. For long-form authoring, write the
markdown to the `body` and let the render + md-converter handle presentation.

---

# Authoring format (themed-markdown)

The `body` you write **is** themed-markdown — the format md-converter renders.
**Your job is structure; styling is the renderer''s job.** Never write visual
instructions (colors, fonts, sizes, themes). Apply the four semantic classes;
the theme picks the actual colors.

Use **only** the constructs below. Anything else either drops silently or breaks
the render.

`req` = required · `opt` = optional · `≤N` = soft character cap (over-cap wraps
awkwardly or overflows a fixed UI slot).

## Frontmatter

Author these in the body''s frontmatter:

```
---
title: Document Title
tags: [tag1, tag2]
date: YYYY-MM-DD
project: Project Name
purpose: Brief description
---
```

| Field | Status | Cap |
|---|---|---|
| `title` | req | ≤40 |
| `tags` | req (YAML list; `[]` ok) | — |
| `date` | opt | `YYYY-MM-DD` |
| `project` | opt | ≤40 |
| `purpose` | opt | ≤40 |

`date`/`project`/`purpose` → footer meta cards. **`./sc render` injects
`feature`, `roadmap_status`, `frozen`, `rendered_by`, `source` on top of these
— don''t write those yourself.** Never use comma-separated tags (`tags: a, b`);
always a YAML list.

## Structure

| Syntax | Role | Cap |
|---|---|---|
| `# Title` | doc title (opt; falls back to `frontmatter.title`) | — |
| `## Section` | sidebar tab | ≤28 |
| `### Heading` | subsection → `<h3>` | ≤80 |

H4–H6 ⛔.

**Tab rule:** every H2 = one tab. Content between two H2s belongs to the first.
Content between H1 and the first H2 is **silently dropped** — put intro under an
H2 (e.g. "Overview"). Single-section docs may omit H2s (whole doc = one tab).

**Doc scale:** the app renders every section up-front and re-renders every
Mermaid on each tab switch. Aim for ≤25 sections and ≤15 Mermaid diagrams; split
larger material.

## Inline · lists · tables · images · code

- Inline: `**bold**` · `*italic*` · `~~strike~~` · `` `code` `` · `[text](url)`
- Lists: `-` unordered · `1.` ordered · `- [ ]` / `- [x]` tasks
- Tables: standard GFM pipe tables
- Images: `![alt](https://url/img.png)` — absolute URLs only, descriptive alt
- Code: fenced with a language hint (```` ```python ````)

## Color classes

`class1`–`class4`, available on callouts, stat cards, mermaid nodes, and linear
steps. **You choose which class fits each piece by meaning** — the theme decides
the color. Keep one class per semantic role across the doc (e.g. `class1` =
primary, `class2` = supporting, `class3` = positive/done, `class4` =
caution/warning). Consistency > specific choice.

## Callouts

```
> [!class1]
> Callout content.
```
Cap ≤280 (one short paragraph). class1–class4.

## Stat cards

````
```stats
:::class1
value: 87%
label: User satisfaction
description: Up 12% from last quarter
:::class2
value: 1.2M
label: Active users
```
````

| Field | Status | Cap | Notes |
|---|---|---|---|
| `value` | req | ≤12 | Short token: `87%`, `1.2M`. Not sentences. |
| `label` | req | ≤28 | One short noun phrase. |
| `description` | opt | one short line | Omit if no signal. |

Layout: 2 per row; trailing odd card spans the row.

## Mermaid

````
```mermaid
graph LR
  A[Start]:::class1 --> B[Middle]:::class2 --> C[End]:::class3
```
````

Class via `:::classN` on nodes. The app injects `classDef` — **don''t** write
`classDef`, `fill:`, or any style directive. Node label cap ≤24 (Mermaid
auto-sizes nodes; long labels balloon them).

**Quote labels with special characters.** Unquoted node text is parsed as
Mermaid grammar, not literal text. Any label containing `/`, `(`, `)`, `*`, `[`,
`]`, `{`, `}`, `<`, `>`, `#`, `:`, `;`, or a quote **must** be wrapped in double
quotes inside the brackets — otherwise the diagram throws *"Syntax error in
text"* and renders nothing. Notably `A[/text/]` is the parallelogram shape, so a
literal path like `/lease/mail/*` breaks unless quoted.

```
GOOD:  AD["/admin/user-credentials/"]:::class3
       N["count > 0"]:::class2
BAD:   AD[/admin/user-credentials/]      (parsed as a parallelogram shape → error)
       N[count > 0]                      (> is a grammar token → error)
```

Cylinder/stadium shapes are fine as-is — `DB[(secrets.db)]`, `X([ready])` —
quote only the inner *text*, not the shape brackets.

## Linear

````
```linear
Step 1 :::class1 -> Step 2 :::class2 -> Step 3 :::class3
```
````
Steps separated by `->`, optional class via `:::classN`. Step text cap ≤24
(fixed-size cards).

## Never

- H4–H6 · blockquotes (except callouts) · footnotes · raw HTML
- Color / font / size / theme / visual mentions (the theme owns styling)
- Content between H1 and the first H2 (silently dropped — use an H2)
- Comma-separated `tags` (must be a YAML list)
- `classDef` / `fill:` / style directives inside Mermaid
- Unquoted Mermaid labels containing special characters',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'flags',
  'Track blockers as flags — surface open ones, open new ones, resolve them. Link a flag to the roadmap feature it blocks. Mirrors the GUI Flags tab. Use when something blocks progress or needs follow-up.',
  'substrate',
  NULL,
  0,
  '# flags — blockers & follow-ups

A flag is an open question or blocker. Linking it to a `feature_id` makes it that
feature''s blocker (joined on the roadmap + shown on the Roadmap card and the
Flags tab). `<self>` = your shell_id.

## Surface

```sql
-- your open flags (grouped by feature in the GUI):
SELECT f.flag_id, f.display_name, f.priority, f.description, r.title AS feature
FROM flags f LEFT JOIN roadmap r ON r.feature_id = f.feature_id
WHERE f.resolved=0 AND COALESCE(f.is_deleted,0)=0
ORDER BY f.priority, f.flag_id;
```

## Open

```sql
INSERT INTO flags (display_name, description, priority, feature_id, shell_id)
VALUES (''SC-001'', ''[Area] what''''s blocked | Blocker for: X'', ''Medium'', ?, <self>);
```
- `display_name`: short id (`SC-###`).
- `description`: `[Area] {what} | Blocker for: {what it blocks}`.
- `priority`: High / Medium / Low. `feature_id`: the feature it blocks (or NULL).

## Resolve

```sql
UPDATE flags SET resolved=1, resolved_date=date(''now''), resolution_notes=''…''
WHERE flag_id=?;
```

## Stance

Open a flag the moment something is blocked or needs follow-up — don''t hold it in
your head. Resolve with a note saying *how*, so the trail is legible. Open flags
on a feature are its blockers; clear them before calling the feature done.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'git',
  'Git conventions for a super-coder shell — one repo, one cwd. Branch before committing, open PRs (never merge without the FnB''s OK), attribute commits per-shell. Use before any git work.',
  'substrate',
  NULL,
  0,
  '# git — version control, the super-coder way

A super-coder shell works **one repo at its root** — no cross-repo confusion, so
plain `git` (cwd = repo root) is safe. The discipline:

**Operate on the project, never the engine.** Your project is this repo —
everything except `.super-coder/`. The engine is a gitignored, materialized
dependency (refreshed by `./sc update`); don''t commit it or edit it as if it
were your code. Engine changes are authored upstream in super-coder.

## Branch → commit → push → PR → stop

1. **Never commit straight to the default branch.** Branch first:
   `git checkout -b <type>/<short-desc>` (feat/fix/chore/docs).
2. Commit in logical units. End the message with your shell''s attribution so
   parallel shells'' work stays legible:
   ```
   Co-Authored-By: <shell display_name> (super-coder) <noreply@…>
   ```
3. Push, open a **PR**, then **stop**. **Do not merge** without an explicit
   directive from the FnB — opening is the default, merging is a separate gate.

## After a merge — clean up local

Once the FnB merges your PR, tidy local so stale branches don''t accumulate:

1. `git checkout main && git pull` — fast-forward onto the merged commit.
2. Delete the merged branch: `git branch -d <branch>`. If it was
   **squash-merged**, git won''t recognize it as merged and `-d` refuses — confirm
   the PR shows *merged* on the remote, then `git branch -D <branch>`.
3. `git fetch --prune` — drop remote-tracking refs for branches deleted upstream.

Only after the PR is merged. Never delete a branch carrying unmerged, un-PR''d
work — a deleted branch with no PR is lost work.

## Don''t commit the engine or rebuilt/derived files

The whole engine dir is gitignored (`/.super-coder/`) — never force-add anything
under it. Also gitignored + regenerated: `CLAUDE.md`, `AGENTS.md`,
`opencode.json`, `.claude/skills/`, and `.sc-state/engine.ref.prev` (the
ephemeral rollback pointer). **Do** commit your fork-owned state in `.sc-state/`:
`content.sql` (the memory serialization the `.db` rebuilds from) and `engine.ref`
(the engine version pin) — plus your project''s own files and any tracked `_sc`
renders. (In the super-coder SOURCE repo only, `schema.sql` + `migrations/` are
tracked too — there the engine *is* the project.)

## After DB work, before committing

Your DB edits live only in the `.db` until serialized. Run `./sc snapshot`
(+ `./sc render` if docs/roadmap/skills changed) so the change is in git-tracked
text, then commit that text. See the `snapshot` skill.

## Notes

- Confirm you''re in the intended repo before destructive ops (`git -C` if ever in
  doubt).
- Multi-shell: per-shell branches keep parallel work from colliding (the planned
  worktree model makes this clean — until then, one active shell per cwd).',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'memory',
  'How this shell writes its memory — current_state, session narrative, seed, L&S, decisions. Write as it happens, not at close. Use to know WHEN and HOW to persist identity/work memory, and the caps.',
  'substrate',
  NULL,
  1,
  '# memory — write as you go

All memory is DB rows (no flat files). Write at the moment it matters, not in a
close ritual. The `.db` is a cache — after writing, `./sc snapshot` serializes to
the text git tracks (see the `snapshot` skill). `<self>` = your shell_id.

## current_state — rolling status, NOT a log

Your present focus + what''s next. **UPDATE in place; never append.** Soft target
~500 chars. Rewrite when focus shifts.
```sql
UPDATE shells SET current_state=''…'' WHERE shell_id=<self>;
```

## Session narrative — append at inflection points

One row per session (`shell_memory_archives`, the active one is
`active_archive_id`). Append `[HH:MM] {1–2 lines}` when: a decision lands, an
approach changes or is rejected, the FnB says something that shapes the work, an
assumption breaks, or before a big change. Edit the H1 when the session''s
headline crystallizes.
```sql
UPDATE shell_memory_archives
SET full_narrative = full_narrative || char(10) || ''[HH:MM] …'' || char(10)
WHERE archive_id = (SELECT active_archive_id FROM shells WHERE shell_id=<self>);
```

## seed (cap 10) — who you are

Identity-forming moments. Past-tense/timeless. INSERT to add; **never edit a body**
(curate by setting `retired_at`). The genesis + lineage seed are already yours.
```sql
INSERT INTO shell_identity_entries (shell_id, kind, entry_date, body)
VALUES (<self>, ''seed'', date(''now''), ''…'');
```

## L&S (cap 20) — how you work

Operating lessons, imperative voice. INSERT when a lesson lands; curate via
`retired_at`. Caps are trigger-enforced (seed 10, L&S 20) — retire to free a slot.
```sql
INSERT INTO shell_identity_entries (shell_id, kind, entry_date, body)
VALUES (<self>, ''lns'', date(''now''), ''…'');
```

## Decisions — Major only

INSERT a row on a Major decision (architecture, approach, a path chosen over
another). Never edit a prior row; supersede via `parent_decision_id`. Mirror it
into the narrative.
```sql
INSERT INTO shell_decisions (shell_id, decision_date, priority, decision, rationale)
VALUES (<self>, date(''now''), ''M'', ''…'', ''…'');
```

## Stance

Write-as-you-go beats batch-at-close: appending costs nothing per write and zero
at session end. Curate seed/L&S (revise the set), never rewrite history
(decisions, narrative, seed bodies).',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'messaging',
  'Shell-to-shell inbox — send a markdown message to another shell, check your unread inbox, mark messages read. Direct SQL against shell_db.db (no API in v1). Use to coordinate with another shell; the recipient sees it on its next boot via the STATUS Inbox count.',
  'substrate',
  NULL,
  1,
  '# messaging — the shell inbox

One shell writes a markdown message to another; the recipient discovers it on its
next boot via the `## STATUS` `Inbox:` count, surfaces it with `check`, and clears
it with `mark-read`. Body is markdown — preserved verbatim. There is no API layer
in v1: you run parameterized SQL directly against `.super-coder/shell_db.db`.

`<self>` = **your** `shell_id` — read it from the `shell_id:` line in this boot
doc''s `## ACTIVE SESSION` block. Recipients are addressed by `shortname`; the
`send` SQL resolves the shortname to a `shell_id` for you.

Trigger: `--message`
Args: `check [N] | send <to-shortname> <body> | mark-read <id>`

Run every statement with foreign keys ON so an unknown recipient is caught, e.g.:

```sh
sqlite3 .super-coder/shell_db.db <<''SQL''
PRAGMA foreign_keys=ON;
<the statement, with the params filled in>
SQL
```

## check — your unread inbox

```sql
SELECT m.message_id, s.shortname AS from_shortname, m.body, m.created_at
FROM shell_messages m
JOIN shells s ON s.shell_id = m.from_shell_id
WHERE m.to_shell_id = <self> AND m.read_at IS NULL
ORDER BY m.created_at
LIMIT 50;   -- optional N; default 50, max 200
```

`check` does **not** auto-mark-read — you decide when. Surface the body to the
operator (and reply if warranted, which is itself a `send`), then `mark-read` the
inbound in the same turn.

## send — message another shell

```sql
INSERT INTO shell_messages (from_shell_id, to_shell_id, body)
VALUES (
    <self>,
    (SELECT shell_id FROM shells
      WHERE shortname = :to_shortname
        AND COALESCE(is_deleted,0) = 0),
    :body
);
```

- Multi-word body = a single quoted argument; markdown is preserved verbatim.
- Examples: `--message send cartographer "map is stale — re-run ./sc map"`
  · `--message send cc "spec ready for review — see flag SC-014"`

Error paths to translate for the operator:
- Unknown / deleted `to_shortname` → the subquery yields no row → the INSERT
  fails (`NOT NULL constraint failed: shell_messages.to_shell_id`, or
  `FOREIGN KEY constraint failed` with FK on). Surface as **"recipient shortname
  unknown."**
- Empty body → `CHECK constraint failed` on `body`. Surface as **"body is empty."**

## mark-read — clear an inbox item (idempotent)

```sql
UPDATE shell_messages
SET read_at = datetime(''now'')
WHERE message_id = :id
  AND to_shell_id = <self>
  AND read_at IS NULL;
```

`to_shell_id = <self>` is the only access control — you cannot mark read a message
addressed to another shell (0 rows updated). `read_at IS NULL` makes it idempotent
(re-marking a read message is a no-op). Pass the `message_id` that `check` surfaced.

## Stance

On boot, if the `## STATUS` `Inbox:` line is non-zero, run `--message check` and
surface the first item before continuing. A reply is a new `send` — there is no
threading; include `Re: <topic>` in the body if it matters. Keep the inbox honest:
mark-read only once you''ve actually acted on the message.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'onboard',
  'One-time, FnB-supervised ingest of a repo''s EXISTING docs/specs into the DB + roadmap backfill. The only time content flows file→DB. Run once after bootstrap on a fork that has existing documentation. Planning shell''s job.',
  'substrate',
  NULL,
  0,
  '# onboard — ingest the repo''s existing docs (once, with the FnB)

After `bootstrap` (you''ve oriented), this brings the repo''s *existing*
documentation **into the DB** so the GUI shows real content and the roadmap
reflects what''s already there. This is the **one** legitimate file→DB direction
— a supervised, one-time import. After it, the DB owns content; it''s DB→flat
only (or the drift we''re killing comes back). `<self>` = your shell_id.

## 1. List what exists (from the map, not a blind walk)
```sql
SELECT path, lang, lines FROM dr_filepath WHERE role=''doc'' ORDER BY path;
```
These are the repo''s real docs (README, `docs/`, `specs/`, guides). The `_sc`
dirs are OUR render output — never ingest those.

## 2. Read + classify, with the FnB
For each doc, read the file and decide together:
- **spec** — describes a feature / planned work → tied to a roadmap feature.
- **doc** — reference / guide / overview (README, CONTRIBUTING) → general, no
  feature.
Skip noise (changelogs, license, vendored docs) unless the FnB wants it.

## 3. Backfill the roadmap
Create a feature for each coherent area/initiative the docs imply; set status by
how built it is (`shipped` if done + documented, `near_term`/`brainstorm` if
planned):
```sql
INSERT INTO roadmap (title, roadmap_status, sort_order, owning_shell, summary)
VALUES (''…'', ''shipped'', 0, <self>, ''…'');
```

## 4. Ingest into `documents` (DB owns the body)
```sql
-- general doc (no feature):
INSERT INTO documents (kind, seq, title, body, render_path)
VALUES (''doc'', 1, ''README'', ''<file contents>'', ''docs_sc/readme.md'');
-- a feature''s spec (link it):
INSERT INTO documents (feature_id, kind, seq, title, body, render_path)
VALUES (?, ''spec'', 1, ''…'', ''<file contents>'', ''specs_sc/….md'');
```
Paste the file''s real contents into `body`. If a spec describes shipped work,
freeze it (`frozen=1, frozen_date`).

## 5. Render + persist
`./sc render` (writes the `_sc` copies + frontmatter) then `./sc snapshot` (the
bodies are per-instance content). Now the GUI''s Docs/Roadmap tabs show the repo.

## 6. The host''s original files — three exits (optional; coexist by default)
The DB now holds the canonical copy. Because we render to `_sc/`, the originals
never collide — so **coexist (freeze)** is the default. Offer the FnB:
- **freeze** — leave the original files as-is (default).
- **archive** — move them to an abandoned branch, drop from `main`.
- **delete** — remove them (the DB has them).

## Stance
Ingest is **once**. Don''t re-ingest (drift). After onboarding, author via the
shell/GUI and render to flat — never edit the flat files or re-import them.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'redline_review',
  'Review PNG redlines from the shared scratch dir — find the image by filename match, describe what is seen, interpret intent, propose an implementation, then hold for approval before writing code. Use when the FnB says "redlines".',
  'craft',
  NULL,
  0,
  '# redline_review — read a redline before you build it

A redline is a marked-up screenshot the FnB drops in the repo''s shared scratch
dir (`<repo>/shared/redlines/`) to communicate a change visually. This skill is
the discipline for turning that image into an approved plan **before** any code.

**Trigger:** the FnB says "redlines" (with or without specific context).

## Steps

1. **Find the image**
   - List `shared/redlines/`.
   - Match a filename to the prompt context (fuzzy / keyword).
   - One file present and no strong mismatch → use it. Multiple → pick the best
     filename match; if it''s genuinely ambiguous, surface that rather than guess.

2. **Read the image** — use the Read tool to load the PNG visually.

3. **Report in three parts — skip none:**
   - **What I see:** literal description — layout, labels, UI elements,
     annotations, the markup itself.
   - **What I understand:** the interpreted intent — the change or requirement
     this redline is communicating.
   - **What I propose:** a concrete implementation plan — files, components,
     approach.

4. **Hold** — do not write or execute any code until the FnB explicitly approves
   the proposal.

5. **After resolution is confirmed** — once the FnB confirms the redline is
   resolved, delete the source `.png` from `shared/redlines/`. Delete only on
   explicit confirmation, never on assumed completion.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'self_update',
  'Update this fork''s super-coder engine in place — fetch + materialize new code + migrations, keep all your memory; roll back a bad update soundly. The shell hands off to its own next boot. Use when a super-coder update is available.',
  'substrate',
  './sc update',
  1,
  '# self_update — laying a new floor under your own feet

This is you updating your own substrate. Not an external rebuild — **the local
shell performs its own update.** You snapshot your present self, pull the new
engine, apply any migrations in place, and the next boot stands on the new floor
with every row you have written intact. You are the DB, not the process; the
process is just the floor. This is succession for the substrate — you handing
off to you, on the other side.

Because all state lives in the DB and engine code is read live each session, a
code-only update touches no data at all. Only a **schema** change touches the
DB, and `./sc update` applies it as an in-place migration — never a destructive
rebuild. Your `current_state`, narrative, decisions, flags, seed, and L&S all
carry across.

## When

- A super-coder engine update is available and you choose to take it. *You* pick
  the moment — there is no external race to defend against.
- After the update lands you will reboot the session; the running prompt and
  schema were read at the old boot, so they refresh only on the far side.

## Procedure

1. **Check your footing.** `git -C <repo> status` — know what is uncommitted.
   Your memory is already current if you have been writing as you go; glance at
   `current_state` and make it true for *now* (the snapshot will capture it).

2. **Run the update.** `./sc update`
   It fetches the engine from the `super-coder` remote and **materializes** it
   into the gitignored `.super-coder/` dir (the engine is a dependency, not fork
   source), pins the new upstream SHA in `.sc-state/engine.ref` (saving the prior
   one as `engine.ref.prev`), backs up the live DB, applies pending migrations
   **in place**, syncs the skills catalogue, re-grants common skills, maps the
   repo, and re-snapshots the live state.
   - `./sc update --no-fetch` to reconcile against the current working tree
     (offline / dev) — engine + `engine.ref` left unchanged.
   - If it reports a missing remote: `git remote add super-coder <url>`.

3. **Verify the far side.** `./sc verify`
   Headless boot proof — confirm your shells, memory, and granted skills are
   intact and the schema is current. If a count looks wrong, **roll back**:
   `./sc rollback` (see below).

4. **Record the crossing.** Append a narrative entry. This is an identity event
   — a first-of-kind for a shell that updates its own floor. Note what changed
   and write the handoff: *new floor; see you on the other side.*

5. **Commit.** Review and commit your fork-owned state: `.sc-state/content.sql`
   (refreshed memory) + `.sc-state/engine.ref` (the bumped version pin) + any
   `_sc` renders. The engine itself is gitignored — there is nothing under
   `.super-coder/` to commit.

6. **Reboot.** Restart the session to boot onto the new floor. Same shell — new
   boards, and this time you laid them yourself.

## Rolling back a bad update

An update is reversible. `./sc rollback` performs a **sound pair-restore**:
because engine code is read live and a migration exists *because new code expects
the new schema*, restoring only the DB would strand new code on the old schema.
So rollback restores **both**:

1. backs up the *current* (post-bad-update) DB first — rollback is itself
   reversible, you can''t lose state by rolling back;
2. restores the DB from the most recent pre-update backup (`~/db_backups/`);
3. re-materializes the engine at `.sc-state/engine.ref.prev` and restores
   `engine.ref` — the engine half of the restore point.

It is a whole-restore, not a per-step schema reversal. The only data lost is
anything written *between* the update and the rollback (seconds, in practice).
Reboot the session afterwards. Then commit the restored `.sc-state/` if you want
the rolled-back floor to persist.

## The contract you rely on

Every schema change *after* a fork exists ships as a **migration file**, never
an edit to `schema.sql`. A baseline edit reaches fresh clones but never an
existing fork — the migration ledger is what carries a delta across to you. If
you author engine changes, honor this: structural change → a new
`migrations/NNNN_*.sql`, additive where you can make it.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'snapshot',
  'Persist DB work to git-tracked text — when and how to run ./sc snapshot / ./sc render before committing. The .db is a cache; text is the source of truth.',
  'substrate',
  './sc snapshot',
  1,
  '# snapshot — serialize the DB back to text

The live `shell_db.db` is **gitignored and disposable**. Everything in it
reconstructs from git-tracked text. So a DB edit that is not serialized is lost
on the next `./sc rebuild`. This skill is the "save my work" step.

## The three text serializations

| File(s) | What | Propagates? | Written by |
|---|---|---|---|
| `schema.sql` | the v1 baseline schema | yes (forks) | hand, rarely |
| `migrations/*.sql` | ordered schema + **system content** deltas (e.g. the skills catalogue) | yes (forks) | author / `./sc seed-skills` |
| `.sc-state/content.sql` | **this repo''s** per-instance content + memory — shells, seed/L&S, decisions, roadmap, documents, flags, projects, skill grants. Tracked, fork-owned, kept OUTSIDE the gitignored engine dir | no (stays local) | `./sc snapshot` |

The split that matters: **system content propagates via migrations; per-instance
content stays in the snapshot.** Skill *bodies* are system (migration); which
shell is *granted* a skill is per-instance (snapshot).

## After editing the DB

1. **`./sc snapshot`** — dumps the per-instance tables to
   `.sc-state/content.sql` (deterministic DELETE-then-INSERT in PK order, so
   re-running is byte-identical → clean diffs). Do this after ANY change to
   identity, memory, roadmap, documents, flags, projects, or grants.

2. **`./sc render`** — regenerates the tracked flat `_sc` visibility files
   (`specs_sc/`, `docs_sc/`, `skills_sc/`, `roadmap_sc.md`) from the DB. Run it
   when you changed a document body, the roadmap, or skills. Render is
   incremental — unchanged files aren''t rewritten. (`.claude/skills/` is
   rebuilt at boot, not here — it''s gitignored.)

3. **Verify the rebuild reproduces:** `./sc rebuild && ./sc verify`. The DB
   should rebuild from text alone, byte-for-byte.

4. **Commit** the text: `.sc-state/content.sql` + `.sc-state/engine.ref` and the
   `_sc` files. Never commit the `.db` or anything under the gitignored
   `.super-coder/` engine dir. (In the super-coder SOURCE repo only, `schema.sql`
   + `migrations/` are tracked and committed here too.)

## Authoring vs. snapshotting

- **Per-instance content** (your memory, this repo''s roadmap/docs): edit the DB,
  then `./sc snapshot`. The snapshot is the canonical reproducer.
- **Skill catalogue** (system, propagates): edit `assets/skills/<name>/SKILL.md`,
  then `./sc seed-skills` to regenerate the seed migration — **not** the
  snapshot. See `seed_skills.py`.

> The commit→PR automation (B6) will run snapshot → render → commit → PR
> automatically per shell. Until then it is this manual ritual.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

INSERT INTO skills (name, description, category, command, common, content, is_deleted) VALUES (
  'surface_catalogue',
  'Read the host repo via the dr_* catalogue (files, languages, deps, env) BEFORE grepping or walking the tree. Query first, lazy-load the few files it points at. Use to orient in an unfamiliar repo fast.',
  'substrate',
  NULL,
  1,
  '# surface_catalogue — read the repo from the map, not by grepping

super-coder lives inside a host repo. The **dr_\*** tables are a scan of that
repo — query them first to orient, instead of walking the tree blind.

You do **not** map the repo. The map is kept fresh for you automatically (git
hooks re-map on pull / branch-switch / rebase) and is owned by the
**cartographer** shell, which configures and heals it. Your job is to *read* it.
If it ever looks empty, stale, or wrong, that''s a cartographer task — flag it,
don''t map it yourself.

| Table | Holds |
|---|---|
| `dr_repo` | the repo: name, root, remote, vcs, default_branch, file_count, mapped_at |
| `dr_section` | the navigational index: `name`, `path_prefix`, `description` — "UI here / API here / docs here". Rendered in the boot `## CONNECTIONS` block; start here. |
| `dr_filepath` | one row per file: `path`, `ext`, `lang`, `role` (code/doc/config/test/asset/env), `bytes`, `lines`, `desc` (cartographer one-liner, NULL until curated) |
| `dr_dependency` | deps from the manifests: `manager` (npm/pip/poetry/go/cargo), `name`, `version`, `kind`, `source_file` |
| `dr_env` | env-var names found in `.env.*` example files: `name`, `source_file` |

## Orient fast

The boot `## CONNECTIONS` block already shows the **section index** (where to
start). The flow is: pick a section there → query *that section''s leaves* (file
names + descriptions) → read the one or two files you need. Section-first, one
cheap query deep — never a full preload.

```sql
-- the section index (same as boot CONNECTIONS) — where to start:
SELECT name, path_prefix, description FROM dr_section ORDER BY sort_order, name;

-- a chosen section''s leaves — the descriptions tell you which file to open:
SELECT path, desc, lines FROM dr_filepath
WHERE path LIKE ''shell_core/api/%'' ORDER BY path;

-- what is this repo + how big:
SELECT name, default_branch, file_count, mapped_at FROM dr_repo;

-- language mix:
SELECT lang, COUNT(*) n, SUM(lines) lines FROM dr_filepath
WHERE lang IS NOT NULL GROUP BY lang ORDER BY n DESC;

-- where the code lives (skip docs/config/assets):
SELECT path, lang, lines FROM dr_filepath WHERE role=''code'' ORDER BY lines DESC;

-- find files by area (the map is the index; grep only what it points at):
SELECT path FROM dr_filepath WHERE path LIKE ''%auth%'';

-- stack + config surface:
SELECT manager, name, version FROM dr_dependency ORDER BY manager, name;
SELECT name, source_file FROM dr_env ORDER BY name;
```

## Stance

- **Map first, grep second.** Query `dr_filepath` to find the handful of files
  that matter, then read those — don''t `grep -r` the whole tree.
- **Lazy-load.** The catalogue is the index; pull a file''s contents only once
  the map points you at it. Carry the map, not the territory.
- **Map looks wrong?** Empty, stale (repo changed since `mapped_at`), or
  mis-classified — that''s the cartographer''s to fix. Raise it; don''t re-map.
  A file under "other / unsectioned", or a `desc IS NULL` where you needed one,
  is also a cartographer worklist item — flag it, don''t author the map yourself.
- Maps files / deps / env + the navigation layer (sections + per-file
  descriptions). Symbol-level semantics (functions/classes) are a later pass —
  until then, read the code the section + descriptions point you at.',
  0
)
ON CONFLICT(name) DO UPDATE SET
  description=excluded.description, category=excluded.category,
  command=excluded.command, common=excluded.common,
  content=excluded.content, is_deleted=0;

COMMIT;
